OpenBazaar/openbazaar-go

core/listings.go

Refactor nested Ifs in for...loop

Refactor listings.go

---

api/tools/api-tools.html
core/core.go

Just testing out the process of forking and submitting code with go projects. Very odd.

Typo Fix and Missing Dependency

---

api/doc.go
api/params.go
api/restapi.go

This is the beginning of documenting out the API for the openbazaar-go server with swagger and OpenAPI spec.
To generate the swagger.json file you do the following:
```
1. Go into the api/ folder
2. Install go-swagger on your machine (follow instructions at https://github.com/go-swagger/go-swagger)
3. swagger generate spec -b . -o swagger.json
4. Import the resulting json file into swagger-ui (https://github.com/swagger-api/swagger-ui)
```
We will also have Travis build out the swagger json file automatically and have our website pull it to update the API docs automatically. I will submit a separate PR for this.

Swagger API Docs Commenting Foundation

---

api/restapi.go
core/core.go
core/follow.go
core/listings.go
openbazaard.go
repo/config.go
repo/init.go

Fixes the issues in #33 + other fmt fixes.

CLEANUP: gofmt all packages.

---

openbazaard.go

Refactor repo path calculation and put OSX data in App Support.

---

repo/config_test.go
repo/testdata/config

I want to contribute something to the new OpenBazaar server and thought unit tests might be good place to start. I chose the config.go file because I was looking for some simple functions to start with.
Please let me know what needs to be changed and what could be improved! Thanks.

adds test for GetAPIUsernameAndPw function

---

repo/config_test.go
repo/testdata/config

these are:
GetAPIHeaders
GetAPIEnabled
GetAPICORS

adds tests to three functions in the repo package

---

docs/install-windows.md

Fleshed out some of the steps to prevent people from potentially getting stuck.

Install instructions update

---

repo/settings.go

This PR capitalized the attributes of the nested attributes within the Settings data structure.

capitalized nested settings attributes

---

openbazaard.go

Add user-agent

---

core/listings.go

Includes changing `Desc` to `Description` for consistency. This may require an equivalent change on the frontend.

Cleanups in Listings.go

---

api/endpoints.go
api/jsonapi.go
core/listings.go
qa/listings.py

Added /ob/listings API that returns empty list if no listing is available, and list of listings otherwise. 
Also qa test for case:
- GET listings on fresh node and check if empty list
- POST listing
- GET listings and check if one listing is returned
Fixes #204

Local API to fetch own listings

---

core/images.go

This updates the values for the header sizes to be correct.
See #158 and #226

Updates the header sizes to the right values.

---

repo/datastore.go
repo/db/settings.go

@cpacia CR please
I want this for tests and this seemed like the best way to implement it. Let me know if you'd prefer another way.

FEATURE: Add Delete() to Settings db store.

---

.gitignore

Ignoring files for Ack and CTags.

TWEAK: Add .ackrc and .tags* to .gitignore.

---

README.md

Just a few typos and other issues.

Fix minor errors in README.md

---

api/jsonapi.go

Allow vendors to refund buyers after the order has been
fulfilled. Also update the error message to be clearer.

Fix issue #184

---

core/order.go

Remove duplicate set of order.RefundAddress

---

api/gateway.go
openbazaard.go

This cleans up server shutdown handling and makes it easy to close.
@cpacia Please review.

REFACTOR: Make API Gateway closable.

---

repo/db/cases.go
repo/db/cases_test.go
repo/db/chat.go
repo/db/chat_test.go
repo/db/db.go
repo/db/followers.go
repo/db/followers_test.go
repo/db/following.go
repo/db/following_test.go
repo/db/inventory.go
repo/db/inventory_test.go
repo/db/keys.go
repo/db/keys_test.go
repo/db/offinemessages.go
repo/db/offlinemessages_test.go
repo/db/pointers.go
repo/db/pointers_test.go
repo/db/purchases.go
repo/db/purchases_test.go
repo/db/sales.go
repo/db/sales_test.go
repo/db/settings.go
repo/db/settings_test.go
repo/db/stxo.go
repo/db/stxo_test.go
repo/db/txns.go
repo/db/txns_test.go
repo/db/utxos.go
repo/db/utxos_test.go
repo/db/watched_scripts.go

Also change all db reads to RLock.

Switch out db mutex with RWMutex

---

api/endpoints.go
api/jsonapi.go
api/notifications/notifications.go
bitcoin/listeners/transaction_listener.go
core/disputes.go
docs/ssl.md
net/service/handlers.go
repo/datastore.go
repo/db/db.go
repo/db/notifications.go
repo/db/notifications_test.go

Notifications

---

openbazaard.go
repo/db/db.go
repo/db/followers.go

This server command returns the status of the repo.. whether it's uninitialized,
encrypted, or decrypted and also whether Tor is avaible to be used as a startup
option.
closes #245

Add server status command

---

docs/install-linux.md

Making things slightly more efficient.

TWEAK: Installing build-essential and git

---

api/jsonapi.go
openbazaard.go
vendor/github.com/ipfs/go-ipfs/core/corehttp/gateway_handler.go

Save the password as a SHA256 hash in the config rather than cleartext.

Hash API password in config

---

parts/plugins/x-go.py

This is a workaround for bug https://bugs.launchpad.net/snapcraft/+bug/1616985 and it requires ppa:gophers/archive

Use a custom plugin to be able to build the snap with go 1.7

---

core/listings.go

TWEAK: Make a constant for coupon title length.

---

api/gateway.go
api/notifications/notifications.go
api/notifications/notifications_test.go
api/notifier.go
bitcoin/listeners/transaction_listener.go
core/core.go
core/disputes.go
net/service/handlers.go
net/service/service.go
qa/smtp_notification.py
qa/test_framework/test_framework.py

Attempt to abstract out notification mechanism into separate part of the service. This PR is currently just for progress tracking purpose. Most commits will be squashed/changed later. Hope to receive comments when it's more or less ready. 
*Update*: Spent some time trying to change as little as possible, but it seems that notifications do need some refactoring (for example interface for integration of dangling `notifications.Notification` type). So started from that.
Task list (checked ones are ready for review):

SMTP (and other) notifications mechanism

---

bitcoin/bitcoind/wallet.go

Simplified `Start()` and `ReSyncBlockchain(fromHeight int32)`, should be easier to maintain in the future if new parameters will need to be passed to the wallet by putting all the logic that was copied and pasted in both methods in a single place.
Cheers.

[DRY] Wallet cmd arguments preparation refactor

---

Makefile
pb/protos/api.proto
pb/protos/contracts.proto
pb/protos/countrycodes.proto
pb/protos/message.proto
pb/protos/moderator.proto
pb/protos/orders.proto
pb/protos/profile.proto

Fix for #344 
Added package declaration to proto-files and a target to makefile.
Note: recompiling protobufs seems to produce a lot of diff, maybe `*.pb.go` files should be updated as well.

Protobuf compilation

---

api/endpoints.go
api/jsonapi.go
bitcoin/bitcoind/wallet.go
bitcoin/listeners/transaction_listener.go
bitcoin/wallet.go
core/refunds.go
repo/datastore.go
repo/db/db.go
repo/db/txmetadata.go
repo/db/txmetadata_test.go
repo/models.go
vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go

Transactions

---

core/order.go

If a user enters duplicate coupon codes in an order, remove the duplicate.
If an order comes in to the vendor with duplicate coupon codes, reject as it
would otherwise take the discount off twice.
closes #346

Handle duplicate coupons

---

api/gateway.go
api/jsonapi.go
api/ws.go
openbazaard.go
repo/config.go
repo/config_test.go
repo/init.go
repo/testdata/config
vendor/github.com/ipfs/go-ipfs/core/corehttp/gateway.go
vendor/github.com/ipfs/go-ipfs/core/corehttp/gateway_handler.go

Add allowedIPs in the API and gateway

---

core/completion.go
core/listings.go

Add rating count and average rating to listing index

---

Godeps/Godeps.json
dummy/images.go
dummy/listing.go
dummy/main.go
dummy/profile.go

Replacement for https://github.com/OpenBazaar/openbazaar-go/pull/518

Ts update dummy

---

api/jsonapi.go
core/images.go

Note this is untested (hoping for the regression test suite and CI to catch any bugs).

refactor images.go and adjust sizes (see issue #349)

---

core/core.go
core/net.go
ipfs/pointers.go
net/retriever/retriever.go
openbazaard.go

Add a routine in the MessageRetrieve to fetch pointers from the gateway in addition
to the dht.

Add optional pointer from gateway

---

repo/init.go

Adding Duo gateway, in particular in light of https://github.com/OpenBazaar/openbazaar-go/issues/391

Add Duo gateway

---

core/completion.go

Also remove redundant `rating_` prefix

Use .json suffix for JSON file

---

api/endpoints.go
api/jsonapi.go
core/core.go
package.json

Equivalent to clearing your browsing history.

Add delete cache API endpoint

---

api/endpoints.go
api/jsonapi.go
core/core.go
net/service/handlers.go
package.json

Fix nil payload bug

---

net/service/handlers.go

Fix bug which added a duplicate sig to the contract.

Delete duplicate disputeClose signature

---

core/order.go

Add additional error handling to Purchase function

---

api/jsonapi.go
api/notifications/notifications.go
bitcoin/listeners/transaction_listener.go
core/disputes.go
net/service/handlers.go
repo/datastore.go
repo/db/db.go
repo/db/notifications.go
repo/db/notifications_test.go

Add additional data to order notifications

---

core/listings.go

Fix create slug bug

---

core/listings.go

Prevent duplicate variant and option names

---

vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go

The NewUnsignedTransaction in btcd doesn't work right. The "fee" it takes as an input is used both to calculate the change amount AND to determine if the change output is dust... which obviously is not correct as dust should use the network default relay fee not the amount paid.
So this duplicates the fuction inside spvwallet and fixes the issue.

Fix bug calculating change value

---

api/jsonapi.go

This fixes a race bug with the `GETModerators` call.

BUGFIX: Fix concurrent map writes.

---

api/jsonapi_data_test.go
api/jsonapi_helpers_test.go
bitcoin/listeners/transaction_listener.go
core/listings.go
core/order.go
test/repo.go

This fixes the remaining issues with misspell. It also picks up a couple of changes applied by my editor to reorder the imports correctly.

Fix issues with misspell

---

core/listings.go

Max rules must be less than MaxListItems (30) and shipping rule ranges must
not overlap.

Add additional shipping rule validation

---

repo/db/settings.go
repo/db/settings_test.go
repo/models.go

Remove language field from settings

---

cmd/init.go
cmd/restore.go
cmd/start.go
openbazaard.go

The restore command will spin up a node and attempt to download your user data
from the network and save it in your root directory. This is helpful if you've
recovered your need from seed (using init) and want to see if you can restore
your store data.

Add Restore command

---

core/order.go
net/networkservice.go
net/service/handlers.go

Handle duplicate order confirmation messages

---

api/notifier.go

Fix bug in smpt notifier

---

cmd/start.go

Optionally serve the IPFS API if the API addr is specified in the config.

Serve IPFS API

---

api/jsonapi_helpers_test.go
api/jsonapi_test.go

Make handling error responses better.

REFACTOR: jsonapi test error responses

---

core/listings.go
qa/purchase_crypto_listing.py
qa/testdata/listing_crypto.json

FEATURE: Add coinType to listings.json

---

Godeps/Godeps.json
repo/db/cases_test.go
repo/db/keys_test.go
repo/db/txns.go
repo/db/txns_test.go
vendor/github.com/OpenBazaar/spvwallet/.travis.yml
vendor/github.com/OpenBazaar/spvwallet/eight333.go
vendor/github.com/OpenBazaar/spvwallet/fees.go
vendor/github.com/OpenBazaar/spvwallet/mock.go
vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
vendor/github.com/OpenBazaar/spvwallet/txstore.go
vendor/github.com/OpenBazaar/spvwallet/wallet.go
vendor/github.com/OpenBazaar/wallet-interface/datastore.go

Integrates changes from: https://github.com/OpenBazaar/wallet-interface/pull/1 and https://github.com/OpenBazaar/spvwallet/pull/32
To make the wallet interface slightly less btc-specific.

Update godeps for wallet-interface changes

---

repo/ipfs_keystore.go

1) It wasn't writing to cache after a cache miss
2) It wasn't reloading cache asynchronously after cache hit which causes a deadlock when issue #1 is fixed

BUGFIX: Fix ipfs keystore caching.

---

api/jsonapi.go
api/jsonapi_data_test.go
api/jsonapi_helpers_test.go
api/jsonapi_test.go
core/disputes.go
net/service/handlers.go
repo/datastore.go
repo/db/cases.go
repo/db/cases_test.go
repo/dispute_case_record.go
repo/dispute_case_record_test.go
test/factory/contract.go
test/factory/dispute_case_record.go
test/repo.go

Completes `prevent resolving dispute after 45 day timeout expires` in #843

Protect expired disputes from being closed

---

core/order.go
qa/purchase_crypto_listing.py
qa/testdata/order_crypto.json

BUGFIX: Allow memos on crypto listings.

---

api/jsonapi.go
core/completion.go
net/retriever/retriever.go
net/service/handlers.go
qa/escrow_release_after_timeout.py
repo/migration.go

Escrow release fixes

---

core/record_aging_notifier.go

Fix for bug that prevents tests in core/ from compiling.

BUGFIX: Fix Errorf statements in core/record_aging_notifier.go.

---

cmd/start.go

Given how the wallet events we're ordered a new node couldn't start because it
tried to load the config file to get the coin type first. This changes the order
so that if the config isn't available yet it just moves on.

Fix coin selection bug in start.go

---

.dockerignore
Dockerfile

Update Docker build to use Go 1.10 and optimize for cache utilization.

Docker optimizations and Go update

---

api/jsonapi.go
api/jsonapi_data_test.go
api/jsonapi_helpers_test.go
core/posts.go
repo/init_test.go
repo/migrations/Migration010_test.go

This code does nothing and should be removed. Please review and merge.

Remove a bunch of dead code

---

api/ws.go
bitcoin/resync/resync_manager.go
cmd/start.go
core/completion.go
core/errors.go
core/fulfillment.go
core/order.go
core/record_aging_notifier.go
ipfs/pubsub.go
repo/db/db.go
repo/db/notifications.go
repo/migrations/Migration010_test.go
repo/notification.go
schema/manager.go
schema/path.go

Another round of linting changes from TS_travis_linting.

Remove unused code, goimports, simplify some code

---

deploy.sh

Reuse build.sh script in deploy.sh.

Cleanup build

---

core/disputes.go
repo/dispute_case_record.go
repo/dispute_case_record_test.go
repo/payout_ratio.go

Optionally use counterparty outpoints in dispute resolution

---

api/jsonapi.go
cmd/convert.go
cmd/start.go
core/disputes.go
core/follow.go
core/fulfillment.go
core/import.go
core/listings.go
core/order.go
core/posts.go
core/profile.go
core/record_aging_notifier_test.go
mobile/node.go
repo/db/inventory_test.go
repo/db/offlinemessages_test.go
schema/configuration.go

Fix a bunch of places where we assign values that are never used. Many are unchecked errors or other bugs, some are just unnecessary and had no use so they get assigned to `_`.

Linting: Fix unused assignments

---

api/jsonapi.go
net/service/messagesender.go
repo/db/coupons.go
repo/init_test.go
repo/migrations/Migration006_test.go

Also combines a string declaration with its assignment.

CLEANUP: Remove some unused code and an unused assignment

---

.golangci.yml
api/jsonapi.go
core/import.go

Check for string values that are used too many times (currently configured to 10).
Refactor 2 recurring strings to encapsulate the values in functions.

CI: Add goconst check to linter

---

repo/db/sales.go

Add a nil check to prevent panic.

[#1196] Prevent panic when *SaleDB.GetByPaymentAddress recieves a nil

---

.golangci.yml
core/record_aging_notifier.go
core/record_aging_notifier_test.go
net/repointer/repointer.go
repo/db/cases_test.go
repo/db/chat_test.go
repo/db/db.go
repo/db/followers.go
repo/db/following.go
repo/db/keys_test.go
repo/db/notifications_test.go
repo/db/offinemessages.go
repo/db/purchases_test.go
repo/db/sales_test.go
repo/db/txns_test.go
repo/dispute_case_record_test.go
repo/migrations/Migration007_test.go
repo/migrations/Migration008_test.go
repo/migrations/Migration014_test.go
repo/notifications_test.go
repo/purchase_record_test.go
repo/sale_record_test.go
schema/configuration_test.go
schema/manager.go
schema/manager_test.go

fix all errors reported by the linter
fixes: https://github.com/OpenBazaar/openbazaar-go/issues/1201

 Enable megacheck linter rules

---

.golangci.yml
api/jsonapi.go
cmd/convert.go
cmd/decrypt.go
cmd/encrypt.go
cmd/restore.go
cmd/setapicreds.go
cmd/start.go
core/listings.go
core/order.go
core/record_aging_notifier_test.go
mobile/node.go
repo/db/sales_test.go
repo/migrations/Migration008_test.go
repo/migrations/Migration013.go

fix all errors reported by the linter
fixes: https://github.com/OpenBazaar/openbazaar-go/issues/1205

Enable unconvert linter rules

---

docs/altcoins.md

Previous link was pointing to a repo that has since been moved into another repo. 
🎃

Update btcrpcclient link

---

core/disputes.go
core/net.go
net/service/messagesender.go
repo/db/notifications.go
repo/notifications_test.go

Fix the last of the misspellings.

CLEANUP: Fix misspellings.

---

README.md

Signed-off-by: Soumya Ranjan Mohanty <soumyacool2012@gmail.com>

Improve README: fix grammar

---

bitcoin/listeners/transaction_listener.go

Fixes #1112
Let me know if it needs more, I followed instructions from the issue @cpacia.

Add nil check to addresses in transaction listener

---

net/service/handlers.go

Save public key in database whenever an offline relay message is received.

HandleOfflineRelay save public key

---

README.md

I made some small changes to the README file, including fixing capitalization, adding commas where appropriate, and slightly rewording some phrases. I hope this helps! ✅

Improved grammar and fixed capitalization in the main README file.

---

core/currency.go

Restore order association on legacy spend

---

core/disputes.go

Currently if the `multisign` function in the `ReleaseFunds` function fails then the contract will save in an incorrect state and the user will not be able to retry. By putting the multisign before the database update we guarantee that if it fails the state will not be updated and the user can retry. 
Also add some more logging.

Change order or tx broadcast and contract save in ReleaseFunds function

---

Godeps/Godeps.json
vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
vendor/github.com/OpenBazaar/multiwallet/client/pool.go
vendor/github.com/OpenBazaar/multiwallet/client/rotation_manager.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/sign.go
vendor/github.com/OpenBazaar/multiwallet/zcash/sign.go

Update multiwallet dependencies

---

Godeps/Godeps.json
vendor/github.com/OpenBazaar/multiwallet/client/rotation_manager.go

Merge fix in https://github.com/OpenBazaar/multiwallet/issues/74
*This is dependent on `ipfsrebase` getting merged first!*

Merge OpenBazaar/multiwallet#74 fix

---

repo/db/purchases.go
repo/db/purchases_test.go

Fix mass DisputeExpiry notifications for an order

---

qa/requirements.txt

Update requests lib in qa package

---

mobile/config.go
mobile/node.go

iOS does not permit filesystem access, need to find another way to support this case on iOS. I was unable to build this with `gomobile` and assume I have some toolchain problems to resolve before I can again.
Would appreciate it if someone could try building the frameworks before accepting this.

Revert mobile logging to file

---

api/jsonapi.go
core/signatures.go
core/signatures_test.go

Improvement intended for #1345

Extract SignPayload and VerifyPayload w unit tests

---

cmd/setapicreds.go

Fix bug running setapicreds command

---

api/jsonapi.go
ipfs/query.go

Fix bug performing type check on DHT

---

core/utils.go

Fix bug returning empty transaction list to GET order API

---

Godeps/Godeps.json
vendor/github.com/OpenBazaar/multiwallet/bitcoin/sign.go
vendor/github.com/OpenBazaar/multiwallet/bitcoincash/sign.go
vendor/github.com/OpenBazaar/multiwallet/client/rotation_manager.go
vendor/github.com/OpenBazaar/multiwallet/client/transport/transport.go
vendor/github.com/OpenBazaar/multiwallet/keys/keys.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/sign.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
vendor/github.com/OpenBazaar/multiwallet/util/balance.go
vendor/github.com/OpenBazaar/multiwallet/zcash/address/address.go
vendor/github.com/OpenBazaar/multiwallet/zcash/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/zcash/sign.go

Includes fix for https://github.com/OpenBazaar/multiwallet/issues/74

Include latest multiwallet bug fix

---

docs/altcoins.md

Need to update document to reflect new architecture used in 2.3.0.

Update docs/altcoins.md with out-of-date notice

---

ipfs/caching_router.go

`master` is broken from #1544. This should fix it.

Fix caching router

---

ipfs/api_router.go
ipfs/caching_router.go
ipfs/config.go
mobile/node.go

Proper network lookup fix

---

cmd/start.go

#1535 Include Daemon Version in log output

---

repo/db/txns.go

Resolve transactions on all exits in repo/db/txns.UpdateHeight

---

cmd/start.go

Added version output back to the standard output.

#1563 VERSION OUTPUT TO STANDARD OUTPUT

---

mobile/node.go
mobile/node_test.go

Configure ipfs global vars in mobile package

---

repo/migrations/Migration023.go
repo/migrations/Migration023_test.go

Fix timestamp shift migration from being reapplied over and over

---

mobile/node.go

Wire up authentication in the mobile package

---

api/jsonapi.go

GET /ob/resolveipns/:peerid can perform self-lookups

---

net/service/handlers.go

[#1645] Prevent notifications produced on MODERATOR_ADD and REMOVE

---

api/jsonapi.go
core/completion.go
core/confirmation.go
core/disputes.go
core/fulfillment.go
core/net.go
core/order.go
core/refunds.go
mobile/node.go
net/service/handlers.go
repo/db/cases.go
repo/db/chat.go
repo/db/chat_test.go
repo/init.go
repo/migrations/Migration011.go

Found a bunch of lint errors while working through #1600. I'm delivering them separately so it's easy to reconcile this merge later.

Additional linter fixes

---

core/core.go
docs/install-linux.md
docs/install-osx.md
docs/install-pi3.md
docs/install-windows.md
package.json

This is the last change due in before 0.13.5 is cut and released. Let's make sure there are no other outstanding items due prior to this being merged.

Bump version 0.13.5 and prepare RC

---

Godeps/Godeps.json
vendor/github.com/OpenBazaar/multiwallet/Gopkg.lock
vendor/github.com/OpenBazaar/multiwallet/Gopkg.toml
vendor/github.com/OpenBazaar/multiwallet/bitcoincash/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
vendor/github.com/OpenBazaar/multiwallet/util/currency.go
vendor/github.com/OpenBazaar/multiwallet/util/fees.go
vendor/github.com/OpenBazaar/multiwallet/zcash/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go

Fixes #1664 
Removes multiwallet dependency on BitcoinCash-Wallet as part of #1671

Merge in multiwallet changes

---

repo/migrations/Migration025.go
repo/migrations/Migration025_test.go

Migration 25 should bump version to 26.

Bump version numbers in Migration025

---

api/jsonapi.go
core/import.go
core/listings.go
core/moderation.go
core/order.go
core/profile.go
core/utils.go
repo/currency_definition.go

Consider node state when returning NormalizedCurrencyCode

---

net/service/handlers.go
vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

This PR makes the changes required for progressing DECIDED disputes to RESOLVED.

Fix eth dispute resolution

---

core/profile.go

Use currency code in profile instead of String() output

---

api/jsonapi_test.go
mobile/cmd/main.go
mobile/node.go

Fixes #1732 
@drwasho if you want to test it out.

Fix restart to wait for stop() to complete first.

---

core/net.go
net/service/handlers.go
net/service/messagesender.go
net/service/service.go

Self-explanatory. Increased and verbose debug messages through order messages.

Increased verbose logging for orders to help track down issues

---

net/service/handlers.go
qa/eth_complete_disputed.py
qa/eth_dispute_close_vendor.py
qa/eth_escrow_release_after_timeout.py
qa/eth_purchase_crypto_listing.py
qa/testdata/eth_listing.json
qa/testdata/eth_listing_crypto.json
repo/sale_record.go
vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

This PR fixes eth qa tests as well as issue 1754.

Fix eth qa tests 

---

net/service/service.go
qa/testdata/digital.json

Fix net.service shutdown panic

---

api/jsonapi.go
api/jsonapi_data_test.go
core/errors.go
core/inventory.go
core/listings.go
core/order.go
core/signed_listings.go
core/signed_listings_test.go
qa/manage_crypto_listings.py
qa/market_price_modifier.py
qa/testdata/listing_crypto.json
repo/datastore.go
repo/db/inventory.go
repo/db/inventory_test.go
repo/listing.go
wallet/listeners/transaction_listener.go

This updates the inventory db interface and implementation to use big ints for inventory and updates all the areas where we do math on inventory. This also gets the crypto currency QA tests passing. 
Should close #1769

Fix bugs handling big inventory

---

repo/currency_definition.go
repo/currency_definition_test.go
repo/listing.go
repo/listing_index.go

Revert back to 'coinType' key in listing index

---

api/jsonapi_data_test.go
core/completion.go
core/disputes.go
repo/currency_definition.go
repo/currency_definition_test.go
test/factory/currency.go

Add blocktime to currency definition

---

vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

This PR fixes the wallet spend error for eth wallet.

check txn receipt for transfer

---

repo/db/sales.go

Fix sales db to use conversion func

---

repo/listing.go

Set version on listing create

---

wallet/listeners/wallet_listener.go

Allow TxMetadata to be missing when recieving a wallet tx

---

core/order.go
core/order_test.go

Use correct currency code when converting crypto prices

---

core/order.go
qa/testdata/order_crypto.json
qa/testdata/order_digital.json
qa/testdata/order_direct.json
qa/testdata/order_direct_too_much_quantity.json
repo/listing.go

fixes #1814 
PurchaseData is now updated to accept a bigQuantity

(#1814) Upgrade repo.PurchaseData to use bigQuantity

---

core/order.go
repo/currency_definition.go

(#1820) Support unknown currencies in market price lookup

---

api/jsonapi_test.go
core/profile.go

(#1823) Fix PATCH /ob/profile to update profile.Currencies

---

repo/listing.go

(#1799) Set default escrow timeout hours on listing create

---

core/listings.go

(#1787) Fix bug setting inventory on own listings

---

api/jsonapi.go
api/jsonapi_helpers_test.go
api/jsonapi_test.go
core/moderation.go
test/factory/settings.go

Closes #1821 
When investigating #1821, found the issue to be mostly resolved when attempting the use case which was described. Did found some opportunities for the panic to continue occuring as well as some other error handling which needed to be corrected. (See commit 6581422 comments for detail.)
Also, a unit test.

(#1821) Improve/protect PATCH /ob/settings

---

core/order.go
core/order_test.go
repo/db/purchases_test.go
repo/db/sales_test.go
repo/db/util.go
repo/listing.go

(#1801) Fix surcharge parsing error on purchase

---

repo/db/cases.go
repo/db/cases_test.go
repo/db/purchases.go
repo/db/purchases_test.go
repo/db/sales.go
repo/db/sales_test.go

(#1810) Correctly set coinType db return only when CryptoListing

---

mobile/node.go

Forgot to properly change DHT detection in mobile build.

Add DHT extraction behavior to mobile build

---

api/jsonapi_test.go
repo/listing.go

(#1844) Allow crypto currency listings with quantity of zero

---

repo/migrations/Migration027.go
repo/migrations/Migration027_test.go
repo/migrations/Migration028.go
repo/migrations/Migration028_test.go

Migration027 migrates all listings and the listing index to the new format.
Migration028 is updated to migrate the inventory table to use strings for
counts.
closes #1718 
closes #1721

(#1718, #1721) Create Migration027 and update Migration028

---

cmd/start.go
core/core.go
core/inbound_message_scanner.go
core/inbound_message_scanner_test.go
core/net.go
net/service/handlers.go
openbazaard.go
qa/eth_escrow_release_after_timeout.py
repo/datastore.go
repo/db/messages.go
repo/db/messages_test.go
repo/db/purchases_test.go
repo/migrations/Migration032.go
repo/migrations/Migration032_test.go
repo/models.go
schema/constants.go
schema/manager.go
test/factory/message.go
vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
vendor/github.com/OpenBazaar/wallet-interface/wallet.go

Store inbound messages too as per issue #1797.

(#1797) Inbound msg persistence

---

api/jsonapi_test.go
core/moderation.go
core/profile.go
repo/currency.go
repo/currency_test.go
repo/dispute_resolution.go
repo/dispute_resolution_test.go
repo/profile.go
repo/profile_test.go
test/factory/currency.go
test/factory/profile.go

(#1839) Validate moderator fee schedule

---

repo/notification.go
wallet/listeners/transaction_listener.go

(#1809) Set payment notification fundingTotal to CurrencyValue

---

repo/init.go
repo/migration.go

(#1868) Add Migration033 to node migration list

---

net/retriever/retriever.go

This one is simple and annoying in the logs.
Thanks @rmisio

Fix formatted logging messages

---

repo/profile.go
repo/profile_test.go

(#1880) Remove validation for non-nil mod info

---

core/disputes.go

(#1877) Add PayoutCurrency to dispute payouts

---

vendor/github.com/OpenBazaar/multiwallet/litecoin/exchange_rates.go

(#1862) Re-enable missing API endpoints for LTC pricing

---

vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

(#1840) Show negative values for outgoing eth transactions 

---

vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
vendor/github.com/nanmu42/etherscan-api/account.go

This resolves Issue https://github.com/OpenBazaar/openbazaar-go/issues/1893.

(#1893) Fix transaction ordering for ETH txns

---

core/images.go
net/retriever/retriever.go
vendor/github.com/OpenBazaar/multiwallet/bitcoincash/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/zcash/exchange_rates.go

Fix to mitigate against #1861 and #1862.

(#1861, 1862) Update vendored transports for Master

---

vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go

Check this out @placer14 for approach.

Re-connect to Watched Addresses on Websocket Reconnection

---

core/core.go
docs/install-linux.md
docs/install-osx.md
docs/install-pi3.md
docs/install-windows.md
mobile/node.go
package.json
vendor/github.com/OpenBazaar/multiwallet/zcash/sign.go

Fixes https://github.com/OpenBazaar/multiwallet/issues/112
Fixes https://github.com/OpenBazaar/multiwallet/issues/113 (which in ob-go fixes #1673)
This is a placeholder pull request to ensure the upstream hotfix is merged into `master` (and `ethereum-master`). Will open the PR for merge once we finalize the hotfix branch for release.

Merge v0.13.7 hotfix

---

Godeps/Godeps.json
vendor/github.com/OpenBazaar/multiwallet/Gopkg.lock
vendor/github.com/OpenBazaar/multiwallet/bitcoin/wallet.go
vendor/github.com/OpenBazaar/multiwallet/bitcoincash/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
vendor/github.com/OpenBazaar/multiwallet/client/pool.go
vendor/github.com/OpenBazaar/multiwallet/keys/keys.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
vendor/github.com/OpenBazaar/multiwallet/zcash/exchange_rates.go
vendor/github.com/OpenBazaar/multiwallet/zcash/sign.go
vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go

Includes latest set of improvements from multiwallet:
- Restore missing error handling
- Add `AddWatchedAddresses` protection changes
- Batch addr subscription
- Restore commented out LTC exchange rate API URLs
- Fix minor spelling and alignment

Vendor latest changes for multiwallet

---

Godeps/Godeps.json
vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/address/address.go

[#1960] Gracefully continue past GetTransactions and GetUtxos errors

---

core/utils.go

(#1803) Fix double negative bug in refundAddressTransaction

---

core/profile.go
repo/currency.go
repo/currency_test.go
repo/profile.go
repo/profile_test.go
test/factory/fixtures/profiles/v0-profile-moderator-fixed-fee.json
test/factory/fixtures/profiles/v4-profile-moderator-fixed-fee.json
test/factory/fixtures/profiles/v5-profile-moderator-fixed-fee.json
test/factory/helper.go
test/factory/listing.go
test/factory/profile.go

Support legacy profiles

---

Godeps/Godeps.json
vendor/github.com/OpenBazaar/go-ethwallet/wallet/client.go

Use the etherscan API key while initializing the etherscan client.

Add etherscan API key

---

vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

Fix eth wallet websocket update height

---

repo/listing.go

(#2003) Fix bug returning coupon discount code for own node

---

repo/db/sales.go
vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

(#2007) Fix eth GetConfirmations height

---

core/disputes.go
net/service/handlers.go
qa/testdata/eth_listing.json
vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

(#2006) Fix vendor contract missing

---

core/profile.go
repo/listing.go

(#1949) Fix patching profile with moderator fee

---

vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

Check error in eth addTransaction

---

vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

Check for nil blocknumber when retrieving tx

---

repo/migrations/Migration016_test.go

Need to update migration to use mainnet instead of testnet.

Fix testnet to mainnet

---

ipfs/pointers.go
net/retriever/retriever.go

Increased logging for pointer retrieval and wait for bootstrapping before ping data node for pointers.

Tweak Pointer Retrieval at Startup

---

repo/notification.go

Currently, we don't unmarshal pre-big.int notifications properly for the client.

Check for pre-bigInt notifications pricing

---

repo/migrations/Migration028.go
repo/migrations/Migration033.go

Not pretty but it would get someone past an already migrated v5 contract upgrade.

Potential fix for migration failures

---

api/jsonapi.go
core/confirmation.go
core/order.go
repo/db/cases.go

Handle legacy contracts

---

api/jsonapi.go
core/order.go
core/spend.go
schema/configuration.go
vendor/github.com/OpenBazaar/multiwallet/bitcoin/wallet.go
vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
vendor/github.com/OpenBazaar/multiwallet/config/config.go
vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
vendor/github.com/OpenBazaar/multiwallet/util/fees.go
vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go
vendor/github.com/OpenBazaar/spvwallet/config.go
vendor/github.com/OpenBazaar/spvwallet/fees.go
vendor/github.com/OpenBazaar/spvwallet/wallet.go
vendor/github.com/OpenBazaar/wallet-interface/wallet.go
wallet/builder.go

The fee estimate endpoint needs to be updated as a predecessor to this PR.
Do not merge until the endpoint has been updated.

[NO MERGE] Add Super Economic to Server

---

api/endpoints.go
api/jsonapi.go
core/listings.go
repo/listing.go

@cpacia the purpose here is to be able to bulk update the price of your listings by a percentage.
```
{
"percentage": <float_percentage>
}
```
The percentage can be negative or positive to increase or decrease the price.

Adjust listing prices by percentage bulk

---

api/jsonapi.go
core/spend.go
vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
vendor/github.com/OpenBazaar/multiwallet/util/fees.go
vendor/github.com/OpenBazaar/spvwallet/fees.go
vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
vendor/github.com/OpenBazaar/wallet-interface/wallet.go

We're currently defaulting to NORMAL.

Change default fee level to ECONOMIC

---

vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go

This is a bug preventing super economic ETH txs.

Need to accomodate super economic fees for ETH

---

api/jsonapi.go
api/jsonapi_data_test.go
api/jsonapi_test.go
api/notifier.go
repo/models.go
test/factory/settings.go

Add Store Name to Email Notifications

---

README.md

Removing a couple flags that don't exist anymore (`bitcoincash` and `zcash`) and adding `forcekeypurge`.

Update README with the latest command flags help output
