- repo/init_test.go
Hey guys, I am trying to write a test for maybeCreateOBDirectories and I encountered a little problem, maybe you can help. When I run this test it fails with this message
```
--- FAIL: TestMaybeCreateOBDirectories (0.00s)
init_test.go:52: drwxr-xr-x
init_test.go:53: -rwxrwxrwx
```
But I would expect the filepermissions to be equal. If you look at line 81 of init.go, the file-permissions of the root-dir are set to `os.ModePerm`. What am I missing here?
> test for init.go maybeCreateOBDirectories

- repo/init.go
- repo/init_test.go
This function proved to be difficult to test. The only way to test the failures of the NewEntropy and NewMnemonic function calls was to use dependency injection in createMnemonic. This provided a way to pass in mock versions of these functions that would fail.
> Test create mnemonic

- core/listings.go
- core/order.go
I've reordered the checks to match exactly `contracts.proto`. It's now much easier to make sure the checks are comprehensive, and makes maintenance much easier.
> Various cleanups to validateListing

- core/order.go
The contract type of value 1 is Listing_Metadata_DIGITAL_GOOD, but it seems we want Listing_Metadata_PHYSICAL_GOOD instead (with value 0).
> Fix bug in order.go

- core/order.go
Fix for #191 and my first PR
As I understand, original intention was to subtract `GetPriceDiscount()` or `GetPercentDiscount()` as percentage from `itemTotal`, if any of those returns non-zero.
> Fix coupon handling in CalculateOrderTotal()

- core/completion.go
- core/confirmation.go
- core/fulfillment.go
- core/listings.go
- core/order.go
- core/refunds.go
- core/signatures.go
Added new file `core/signatures.go` that contains two functions for verifying message and bitcoin signatures respectively. Verification is delegated to `verifyMessageSignature()` via closure argument that
captures logic for extracting signatures from contract context. Also, some imports rearrangement due to `goimports` tool.
Seems to be 150+ lines of code diff, so code review would be very much appreciated.
> Move signature verification to dedicated function

- core/follow.go
- core/listings.go
- core/profile.go
Abstracted profile counts updating into the method `updateProfileCounts()` in `core/profile.go`, that is called from `DeleteListing()` and `UpdateFollow()` methods (where counts recomputation is needed).
Fix for #228
> Update profile counts when needed

- snapcraft.yaml
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.
> Add the packaging metadata to build the openbazaar daemon snap

- core/core.go
- ipfs/add.go
- ipfs/add_test.go
- ipfs/blocks.go
- vendor/github.com/ipfs/go-ipfs/core/corehttp/gateway_handler.go
Currently PUT is kind of hard to work with and requires many back and forth
messages to upload a directory. Additionally, we don't really want nodes who
are pushing to the gateway to have to upload their entire directory each time as
this wastes bandwidth.
This commit changes the put handler to accept a directory hash. The gateway then traverses the graph, downloading only those nodes it doesn't have. 
The downside to this approach is if client has firewall issues, the gateway might not be able to get files from the network. Possibly we might want to force an outgoing connection to the gateway node if one doesn't exist.
> Change IPFS gateway PUT handling

- net/encryption.go
> Fix net.Encrypt() to use correct MAC key size

- core/core.go
- core/net.go
- core/order.go
See #272. core.EncryptMessage now takes a pointer to a public key as its second argument. If left nil, an IPFS lookup is done for the public key. Most functions in core/net.go now take advantage of this feature, mostly by looking in the contract; SendOrderConfirmation, SendCancel + SendReject (both via datastore lookup for public key), SendRefund, SendOrderFulfillment, SendOrderCompletion.
I have chosen to use libp2p.PubKey throughout, arguably instead we could use []byte, and finally unmarshal in core.EncryptMessage, and this would mean we don't need to import libp2p in net.go. I am not sure what the best option is.
> Adapt core.EncryptMessage to optionally take a public key

- bitcoin/bitcoind/wallet.go
- bitcoin/wallet.go
- core/confirmation.go
- core/order.go
- net/service/handlers.go
- vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
SweepMultisig functions in bitcoind and spvwallet can now optionally take specific address, defaulting to their internal address as before. Purchase() can now also optionally take a refund address in its json input, defaulting to the internal address - previously the external address was used, which likely would lead to bugs. All buyer calls of SweepMultisig now use the address stored in the purchase contract, instead of letting the Sweep function supply the internal address. I have not added an equivalent ability for sellers to provide a custom address on confirmation of offline orders, but this isn't a bad idea.
This resolves issues #282 and #283
> Allow optional user-supplied refund address on purchase, make internal vs external address use consistent, always use refund address from contract

- docs/ssl.md
Updating the SSL documentation to direct the user to set the server certificate name to the server IP. Without this, you will be unable to connect.
> Ssl doc update

- bitcoin/exchange/bitcoinprices.go
> TWEAK: Use ticker.openbazaar.org for bitcoinaverage.com data.

- api/endpoints.go
- api/jsonapi.go
- core/profile.go
- qa/patch_profile.py
Solves #314 
`PatchProfile` function accepts patch data from request as a `map[string]interface{}` and reads old profile data, merging both maps using [mergo (https://github.com/imdario/mergo)](https://github.com/imdario/mergo) library. I hope that added dep is not an issue, but if it is, I will be glad to reimplement it on demand.
Also, I failed to add `mergo` package to `vendors/` because I'm facing an error that says `godep: Package (github.com/OpenBazaar/go-blockstackclient) not found`. Any suggestions?
> PATCH method for Profile API

- core/completion.go
- core/follow.go
- core/listings.go
- core/profile.go
- openbazaard.go
- repo/db/cases.go
- repo/db/inventory.go
- repo/db/pointers.go
- repo/db/purchases.go
- repo/db/sales.go
- repo/db/stxo.go
- repo/db/txns.go
- repo/db/utxos.go
- repo/db/watched_scripts.go
- storage/selfhosted/selfhostedstorage.go
Felt like some regex today, so fixed #211 with this one:
```bash
find -name '*.go' -not -path 'vendors/*' -exec perl -i -p0e \
's/(defer [a-zA-Z0-9]+.Close\(\)\n)(\s+)(if err != nil \{.*?\}\n)/\3\2\1/s' \
{} \;
```
😃
> Fix defer and error check ordering

- core/completion.go
- core/disputes.go
- core/fulfillment.go
- core/net.go
This PR completes earlier work I did to change net functions to use public keys when they are known. Public keys for `SendOrderFulfillment`, `SendOrderCompletion`, `SendDisputeOpen`, `SendDisputeClose` can now be passed in; in all cases, the places where where they are called have access to contract holding the relevant public key (the only exception is `SendDisputeOpen` when sending to a moderator). 
The most obvious benefit of this is that a vendor can interact with a buyer who is not publishing their public key to ipfs; all interactions with the buyer now use the public key as provided in the initial BuyerOrder.
The only functions still forced to do an ipfs lookup are:
`SendChat`, `SendOfflineAck`, `Follow`, `Unfollow`, all of which are not connected to a contract holding a public key. …
> Use contract public key for entire contract state machine

- core/listings.go
The coupon code should have a maximum, otherwise users can add very long strings (I tested with two paragraphs of lorem ipsum). 
This sets the max to 20.
If this PR is accepted, we will need to do the same validation on the client.
> Add a max of 70 characters to the coupon code.

- openbazaard.go
- repo/config.go
The ipfs websocket transport allows the browser to connect directly to ipfs nodes for online communication. The ipfs basichost has this transport enabled by default, but we need to add the relevant address to the swarm. This means that Duo browser clients, or anyone else for that matter, can engage in online comms. I am in the process of testing this and have already had a lot of success sending messages from js to an OB node with this websocket address enabled. This will greatly improve the usability of browser clients.
Fortunately, we can enable this transport in two lines!
> Listen on websocket transport

- repo/config.go
Looks like we've had the wrong PeerID for a while
@JustinDrake
> Change Duo Bootstrap Peer ID

- core/net.go
Reasons for reducing the prefix length to 14 bits:
* Increase deniability (Realistically the network will grow to less than 100,000 active nodes within the first year. Using 16 bits gives a very poor deniability ratio of 100,000/2^16 < 1!)
* Maintain room for growth (I am assuming nodes can bear an 8-to-1 deniability ratio. With 14 bits, that means the network can grow to 8*2^14 = 131,072 active users before the default prefix length will need changing. This is at least one year after launch.)
* It reduces the number of prefixes which makes DHT crawling for prefixes significantly easier for partners such as Duo.
> Reduce default prefix length to 14 bits

- api/jsonapi.go
- net/service/handlers.go
- repo/config.go
- repo/datastore.go
- repo/db/chat.go
- repo/db/chat_test.go
To prevent the server from sending read messages to the other chat party if the
UI calls MarkChatAsRead more than once, let's check to make sure the status
changed before sending the message.
> Only send read message if read status changes

- bitcoin/exchange/bitcoinprices.go
- bitcoin/exchange/bitcoinprices_test.go
factored redundant `fetch()` implementations and common code in `decode()` implementations.
All `ExchangeRateProviders` are now initialized as such but each one has a different implementation of the `ExchangeRateDecoder` interface. 
Each one of `ExchangeRateDecoder` is formalized as an empty `struct` that then implements the minimum code necessary to extract the data parsed by the `JsonDecoder` now invoked only once on `fetch()`
> [refactor] bitcoinprices.go

- core/moderation.go
- core/net.go
- ipfs/pointers.go
- net/service/handlers.go
- repo/datastore.go
- repo/db/db.go
- repo/db/pointers.go
- repo/db/pointers_test.go
To prevent a malious peer from sending us an ACK to a message not intended for
him, thus causing us to prematurely stop re-publishing pointers, let's save
the recipient's ID in the db with the pointer and check it against the peer ID
when receiving and ACK.
closes #355
> Validate peer ID before deleting pointer

- net/service/messagesender.go
- net/service/service.go
As discussed with @cpacia, add a new mechanism for stream reuse; when a peer sends an online message to you, this stream is never closed (barring errors), and all future communication can go back and forth over this stream.
This means that the following groups can now receive online messages where previously they could not:
1. Users behind heavy nats
2. Users connecting from a browser implementation of libp2p 😉 
All they need to do is initiate a connection first, eg with a chat message. Given that it is mostly buyers with networking challenges, and mostly buyers initiating communications, this is a great solution.
The code is modelled (read: shamelessly taken) from the implementation of stream reuse used by the libp2p kademlia-dht implementation; all peers are assigned 'messageSender' …
> Reuse streams for all messaging

- bitcoin/bitcoind/wallet.go
- bitcoin/wallet.go
- core/confirmation.go
- repo/db/keys.go
- repo/db/keys_test.go
- vendor/github.com/OpenBazaar/spvwallet/datastore.go
- vendor/github.com/OpenBazaar/spvwallet/keys.go
- vendor/github.com/OpenBazaar/spvwallet/wallet.go
Orders need to go to a unique address in order for the listener to determine
what order they are for. This would normally be OK except scenarios where someone
has placed a direct order but hasn't paid (or two direct orders come in at the same time).
So we need a wallet function that returns a new address each time. Sadly this
can make it such that malicous buyers can place unfunded orders and run up
the size of the lookahead window in the keychain making it unlikely if not impossible
for all transactions will be detected when restoring from seed.
This can be fixed by either adding the lookahead window size to the config (TODO)
and implementing better DoS protection for unfunded orders.
> Add NewAddress wallet function

- openbazaard.go
This allows js ipfs nodes to connect to go-ipfs nodes, which paves the way for browser openbazaar implementations 😛 (spdy stream muxer doesn't work in js ipfs at the moment) . multiplex is already enabled by default in ipfs 0.4.7 in the daemon (ie when run from command line), but is not enabled in default repo config when using ipfs as a go import yet.
> enable multiplex stream muxer

- api/jsonapi.go
- core/completion.go
- core/confirmation.go
- core/disputes.go
- core/fulfillment.go
- core/order.go
- core/profile.go
- core/refunds.go
- net/service/handlers.go
- repo/db/cases_test.go
- repo/db/purchases_test.go
- repo/db/sales_test.go
this allows nanosecond granularity in message ids, which fixes the very regular message id collision errors
> embrace timestamp conversion functions

- net/service/service.go
This prevents an infinite error loop if the counterparty closes the stream.
> Return from stream handler on stream close

- net/service/messagesender.go
- net/service/service.go
Apologies for yet another stream reuse fix. This prevents the closing of outbound streams after a message is sent.
> Don't close outbound streams

- vendor/github.com/mutecomm/go-sqlcipher/sqlite3.go
This should remove #224 even though it was already closed. 
An even better solution would be to update the vendored module for sqlite3 but this suppresses the warnings for now to remove confusion.
> Ignore deprecation warnings in sqlite3

- core/moderation.go
- core/net.go
- ipfs/pointers.go
See #484, this has magic ids derived from the message ciphertext hash for offline messages, and the peerID for moderator pointers.
> Use deterministic magic ids

- api/jsonapi.go
- core/profile.go
Given the slow speed of ipns calls there are some places where we can probably
get away with loading a profile from cache.
This commit adds a `usecache` argument to the `FetchProfile()` function which will
load the last IPNS record from the datastore and use that in an IPFS cat call
(which should pull from the disk cache). At the same time a goroutine fires
fetching the most recent profile and updating the cache so that the next time
`FetchProfile()` is queried the cache will have the update. In this sense the `usecache`
argument returns a profile that is always one update behind (though given that
profiles don't update with high frequency most of the time it will be the latest).
> Add profile caching

- Godeps/Godeps.json
- api/notifier.go
- repo/db/db.go
- repo/db/keys.go
- repo/db/keys_test.go
- vendor/github.com/OpenBazaar/spvwallet/blockchain.go
- vendor/github.com/OpenBazaar/spvwallet/checkpoints.go
- vendor/github.com/OpenBazaar/spvwallet/datastore.go
- vendor/github.com/OpenBazaar/spvwallet/keys.go
- vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
- vendor/github.com/OpenBazaar/spvwallet/txstore.go
- vendor/github.com/OpenBazaar/spvwallet/wallet.go
Most of the change is to the spvwallet lib, but it does push up a refactor of the keys db implementation. 
Keys used to be fetched from the db by giving the corresponding scriptPubKey. Since segwit introduces a new kind of scriptPubKey, and if a user resyncs the chain from seed we wont know which scriptPubKey to use. 
So this changes it to save the hash160 instead of the scriptPubKey since segwit addresses use the same hash160. 
Keys can now be fetched by giving the hash160, which makes the keys db agnostic to segwit. 
This will likely require resetting the data directory.
> Segwit prep: refactor keys db

- Godeps/Godeps.json
- core/core.go
- package.json
- vendor/github.com/OpenBazaar/spvwallet/README.md
- vendor/github.com/OpenBazaar/spvwallet/blockchain.go
- vendor/github.com/OpenBazaar/spvwallet/eight333.go
- vendor/github.com/OpenBazaar/spvwallet/headers.go
- vendor/github.com/OpenBazaar/spvwallet/makefile
- vendor/github.com/OpenBazaar/spvwallet/peers.go
- vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
- vendor/github.com/OpenBazaar/spvwallet/timesorter.go
- vendor/github.com/OpenBazaar/spvwallet/wallet.go
- vendor/github.com/cevaris/ordered_map/.gitignore
- vendor/github.com/cevaris/ordered_map/.travis.yml
- vendor/github.com/cevaris/ordered_map/LICENSE.md
- vendor/github.com/cevaris/ordered_map/Makefile
- vendor/github.com/cevaris/ordered_map/README.md
- vendor/github.com/cevaris/ordered_map/key_pair.go
- vendor/github.com/cevaris/ordered_map/node.go
- vendor/github.com/cevaris/ordered_map/ordered_map.go
Adds an in-memory cache of 100 blocks to improve validation speeds and make it easier to calculate MTP in the future. 
It also fixes a bug calculating the common ancestor in certain types of reorgs.
> Spvwallet - Improve blockchain handling

- core/core.go
- package.json
- qa/cancel_direct_offline.py
- qa/complete_disputed.py
- qa/complete_moderated_online.py
- qa/complete_moderated_with_timeout.py
- qa/dispute_close_buyer.py
- qa/dispute_close_split.py
- qa/dispute_close_vendor.py
- qa/escrow_release_after_timeout.py
- qa/purchase_direct_offline.py
- qa/refund_direct.py
- qa/refund_moderated.py
- qa/reject_direct_offline.py
- qa/reject_moderated_offine.py
The QA package was mostly only checking that the wallet recorded an unconfirmed
payment and was missing the case where the payment was rejected by the bitcoin
network and failed to confirmed.
This commit updates the package to check the confirmed balance whenever checking
to make sure the funds were received correctly.
> Update QA tests to check for confirmed payouts

- mobile/node.go
- openbazaard.go
- vendor/github.com/ipfs/go-ipfs/core/bootstrap.go
Bootstrapping an IPFS node currencly blocks the OpenBazaar node from starting
for about 10 seconds. This commit runs the bootstrapper in a new goroutine
so that the rest of the OpenBazaar app can move on with its life.
> Run IPFS bootstrap in its own goroutine

- core/confirmation.go
- net/service/handlers.go
The point of confirming an offline order is to just accept whatever amount is
offered in the order. However, the code was re-calculating the order total causing
the vendor to reject the order in some instances.
> Fix bug confirming offline order

- docs/install-pi3.md
https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/install-linux.md & https://freedomnode.com/blog/80/how-to-install-and-configure-new-openbazaar-2-0-on-linux-and-mac-os-x wasted hours of my time & my rPi3 cycles & bandwidth. This is all what actually worked for me.
> Add docs/install-pi3.md

- Godeps/Godeps.json
- api/endpoints.go
- api/jsonapi.go
- api/jsonapi_data_test.go
- api/jsonapi_test.go
- bitcoin/bitcoind/wallet.go
- vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
- vendor/github.com/OpenBazaar/wallet-interface/wallet.go
Refactors the estimate fee API to take in an amount and return the estimated
fee to spend that amount from the wallet. Also adds a new API call to get
the current fee levels.
> Improve fee estimation API calls

- core/net.go
Since the offline message pointer publish was moved into a separate goroutine
the context was being defer canceled before the publish was finished. This
move the defer inside the goroutine.
> Fix cancel bug publishing pointers

- openbazaard.go
Add an option to disable file logging and also wire up the loglevel option.
> Add logging options

- core/core.go
- mobile/node.go
- openbazaard.go
Prevent user publishes from blocking the message retreiver from crawling the DHT
on startup. User publishes can be processed after startup is complete.
> Lock publishes on startup

- docs/ssl.md
It's been observed that if you have multiple certs with the same name, the one you don't want to be used may be used. To avoid this, I've renamed the cert file that the client must install to a more specific name.
> Renaming the client cert file

- core/core.go
- mobile/node.go
- openbazaard.go
- repo/config.go
- repo/config_test.go
- repo/init.go
- repo/migration.go
- repo/migrations/Migrations003.go
- repo/migrations/Migrations003_test.go
- repo/testdata/config
- vendor/github.com/ipfs/go-ipfs/core/builder.go
- vendor/github.com/ipfs/go-ipfs/core/commands/dht.go
- vendor/github.com/ipfs/go-ipfs/core/core.go
- vendor/github.com/ipfs/go-ipfs/namesys/routing.go
Adds a new config file option to specify how frequently the user/store data
is republished to IPNS. There is a tradeoff between the desire to have your
data cached on as many nodes as possible and having the latest content (such as
ratings) visible. The config options allows users make this tradeoff according
to their preferences.
> Add RepublishInterval config option

- Makefile
Makes updating the Docker images easier.
> TWEAK: Make Docker build version default to latest git tag.

- core/listings.go
> Prevent overlapping shipping rule range for quantity discount

- docs/altcoins.md
The link was pointing to bitcoin/wallet.go which has probably
been moved.
Changed the link to point to OpenBazaar/wallet-interface
repository instead.
> Fix link to wallet interface in altcoins.md

- docs/multipleInstances.md
Adds documentation for running multiple instances, so we have easy instructions when people ask about it.
> Multi server doc

- api/jsonapi.go
The current implementation of the JSON API does not handle true Cross Origin Resource Sharing (CORS) support. 
When making an AJAX call using Basic Authentiation, a preflight OPTIONS header is sent before the actual GET request. An OPTIONS header does not/can not contain the Authorization Token. Only the GET request can contain the token. The current implementation does not respond to CORS OPTIONS or GET calls.
There are two changes in the PR:
* Change the `Access-Control-Allow-Methods` to allow GET and OPTIONS HTTP methods.
* Respond to OPTIONS headers with an HTTP status of `200 - OK`. This permits the client to *then* send the actual GET request with the authorization token.
The changes in this PR solve Issue #761
> Allow CORS access to the API by fixing Prelight Header Handling.

- core/listings.go
Gives users and search providers the data they need to filter out listings according to the currency the vendors accept.
> Add 'acceptedCurrencies' array to GET /ob/listings

- docs/ssl.md
Updating the client certificate name to match the file it's output to. This is needed for it to work properly (at least on osx - high sierra).
> updating the client cert name

- net/retriever/retriever.go
- openbazaard.go
Recator the wait group that is part of the message retreiver so we can block
shutdown if we're in the middle of processing transactions.
> Refactor Message Retreiver waitgroup

- net/service/handlers.go
go report reported a typo in `net/services/handler.go`. 
(sorry for the really stupid pull request, I'm still dipping my toes into open-source contribution)
> fixed typo

- net/retriever/retriever.go
- openbazaard.go
When shutting down the message retriever use a done chan that will prevent
blocking until the IPFS timeout is reached. This must be done before the
pointer is recorded in the DB so that we will attempt another download on
next startup.
> Add DoneChan to message retriever

- bitcoin/resync/resync_manager.go
- cmd/start.go
- net/retriever/retriever.go
- qa/purchase_moderated_offline.py
- qa/test_framework/test_framework.py
Currently the MessageRetriever waits until all messages are downloaded before
passing them to the respective handlers. This has two issues. One, message
downloads can take up to five minutes to time out meaning that previously
downloaded messages may not get processed for at least five minutes. Impatient
users might close out the app assuming it's not working right.
Second this blocks the wallet from starting up which again could be up to five
minutes.
This commit refactors the MessageRetriever so that it attempts to process messages
immediately unless the message was received out of order. Only then is it put on
a queue to be processed later. For the vast majority of messages this should mean
the process instantly. Second, since the SPV wallets can make use of the
ResyncManager we don't …
> Refactor MessageRetriever

- api/jsonapi.go
The buyer side is not currently handling this correct so we'll disable for now and circle back later.
> Disallow refunds when in a disputed state

- bitcoin/zcashd/wallet.go
- cmd/start.go
- core/confirmation.go
This refactor allows us to resync zcash from a specific height rather than restarting
the binary with the -rescan flag and rescanning from genesis.
Since this now works we can hook up the resync manager to zcash.
> Refactor zcash resync function

- .dockerignore
- Dockerfile
- Dockerfile.dev
- docker-compose.yml
I've bumped the go version number and created a `dev` docker service to use for development and debugging purposes. You can `docker-compose run dev` to start go environment with openbazaar as the current working directory complete with python and go dependancies for testing.
> Update to Dockerfile to build on go 1.9; dev service in docker-compose

- docs/ssl.md
fixes https://github.com/OpenBazaar/openbazaar-go/issues/801
> server.crt should expire after 1024 days, not openssl default of 30 days

- api/jsonapi.go
- bitcoin/bitcoind/wallet.go
- bitcoin/zcashd/wallet.go
- cmd/start.go
- core/core.go
- core/listings.go
- core/order.go
- qa/reject_disputed_escrow_release.py
This abstracts some methods for testing which mode the node is running in. This begs the question whether the modes are mutually exclusive or not. Then we use the abstractions to protect escrow from being released while the order is in dispute.
> [#843] Guard escrow during dispute

- core/listings.go
- core/posts.go
It's tiny changes.
I thought the `verifySignature` function (`core/signatures.go`) doesn't return `noSigError` type.
> Remove unexpected error cases

- core/order.go
Server was panicking because `contract.BuyerOrder` was not available for validation checks at the end of the method.
> [#871] Make BuyerOrder available for validation checks

- cmd/encrypt.go
the message to provide the password on the command line is a
bit misleading, as it is also possible to provide the password
via stdin when invoking 'start'
providing it via stdin has the advantage not to be visible later
in the shell's history
Signed-off-by: Maximilian Meister <mmeister@suse.de>
> cmd/encrypt: enhance success message

- core/completion.go
- core/disputes.go
- core/record_aging_notifier_test.go
- repo/db/cases.go
- repo/db/sales.go
Completes `prevent dispute from being opened 45 days after purchase/sale` in #843 
This does not include a unit test due to the external `Wallet.GetConfirmation()` dependency. A solution to this in the short term might be to create a fake which meets the Wallet interface but allows the internal state to be manipulated (like forcing certain responses). This scope is too large for this feature and recommend considering this as technical debt for later.
This also fixes a bug that @jjeffryes found when toying around with new timeout values and the new values not being considered in the SQL lookup.
> Protect disputes being opened on orders which are old

- api/jsonapi.go
Completes `GETBalance API endpoint should return current block height` in #843
This could probably be quickly tested with a FakeWallet implementation with the right values stubbed in. Would just need a nice way to create the Node with our FakeWallet. LMK if you guys agree to do this tech debt and I'll add the issue.
> [#843] Add height to /wallet/balance API response

- api/jsonapi_data_test.go
Introduced by commit d9239a5ec6abd2a138ed755b06f13ae3a8fae12e
This value appears to be fixed in vendor/github.com/OpenBazaar/spvwallet/checkpoints.go:59 so it's probably not going to change until the vendored package does.
> [#843] Hasty modification broke the /ob/wallet/balance API test

- core/record_aging_notifier.go
- core/record_aging_notifier_test.go
- test/factory/dispute_case_record.go
- test/factory/purchase_record.go
Fixes #959 and applies to #843 .
When a set of notifications are produced at the same time, the order by
timestamp is undefined. This commit varies the produced notifications'
createdAt timestamp by a second to produce the desired sort in this
special case.
This path was chosen because:
1) the data we intend to sort on is marshalled in SQL and unable to be
sorted in the database.
2) Notifications().GetAll() call probably shouldn't be aware of any
specific notification content for the sake of sorting.
3) This change was minimal for support and testing purposes until the
ExpiresAt data can be sorted in SQL should we decide to pay that debt
> Fix BuyerDisputeTimeout and DisputeExpiry notification order

- api/jsonapi.go
PATCH operations do not work under CORS restrictions without this added.
> Add PATCH to CORS approved methods

- api/jsonapi.go
- api/jsonapi_test.go
- repo/sale_record.go
- repo/sale_record_test.go
- test/factory/contract.go
Completes `return error on POSTReleaseEscrow when Node uses ZEC` in #843
> Ensure calls to POST /ob/releaseescrow w ZEC sales fail

- repo/db/cases.go
Resolves `Improve generateModeratorDisputeExpiryNotifications to handle missing vendor and/or buyer contract` in #843
Note: This PR should remove the first commits that change the duration timeouts before merging.
> [#843] Improve generateModeratorDisputeExpiryNotifications to handle missing vendor and/or buyer contract

- api/jsonapi.go
- cmd/start.go
- core/record_aging_notifier.go
- core/record_aging_notifier_test.go
- repo/constants.go
- repo/db/purchases.go
- repo/purchase_record.go
- repo/sale_record.go
- test/factory/purchase_record.go
Some cleanup of constants and allow test mode to shorten the interval of the `RecordAgingNotifier` as well as the period between notifications produced by that worker: `BuyerDisputeTimeout`, `VendorDisputeTimeout`, `ModeratorDisputeExpiry` and `BuyerDisputeExpiry`
> 843 fix notification interval constants

- repo/migrations/Migration008.go
- repo/migrations/Migration008_test.go
Data stored in the DB is mashalled as a JSON-serialized protobuf and not
as binary data. This migration was failing when attempting to migrate
real data created.
> [#843] Fix Migration008 to use jsonpb Marshaling

- bitcoin/bitcoind/wallet.go
- bitcoin/zcashd/wallet.go
Remove the redundant Params func call because params struct is already embedded inside the wallet implementation and is used everywhere else.
> Remove the params call

- .travis.yml
- repo/db/cases.go
- repo/db/purchases.go
- repo/db/sales.go
- repo/migration.go
Simple bugfixes
- `tx.Commit()` returns and error so this should be propagated
- Migrations only use a single bytes for writing the repo version to disk (in ASCII). This means migrations don't work after 9. This should allow a full int
- There is no need to check gofmt'ing on protobuf generated Go code because it shouldn't be changed even if it violates gofmt rules.
> Bugfixes: Error propagation, migrations version fix, no gofmtcheck for pb's

- core/disputes.go
- core/record_aging_notifier_test.go
- repo/db/cases.go
- repo/db/cases_test.go
This ensures only Dispute Cases which are currently in dispute will emit notifications.
> [#1035] Resolved Dispute Cases should not emit expiry notifications

- .gitignore
Add .vscode directory to .gitignore to make it more difficult for devs using VSCode to accidentally commit it.
They could all manually set git up globally to ignore it, but the % of people that do that is probably very small.
> CLEANUP: Add .vscode to .gitignore.

- api/jsonapi.go
This commit adds an optional query parameter allowing clients to pass in an
ID used for async requests where the response is returned over websockets.
The current approach of generating and returning a random ID may create a race
condition causing the client to miss the response.
closes #925
> Add optional asyncID query param to async API calls

- Dockerfile.dev
Cherry-pick Docker.dev changes from 7e041843258c0af48d3ebdc21c40ce87e86c37be in PR #981.
> Support `make protos` in development docker image

- api/jsonapi.go
- cmd/restore.go
- cmd/start.go
- core/images.go
- core/ipns.go
- core/order.go
- core/profile.go
- ipfs/cat.go
- ipfs/dag.go
- ipfs/resolve.go
- mobile/node.go
- net/retriever/retriever.go
- vendor/github.com/ipfs/go-ipfs/namesys/namesys.go
- vendor/github.com/ipfs/go-ipfs/namesys/pubsub.go
- vendor/github.com/ipfs/go-ipfs/namesys/routing.go
Major refactor of IPNS code. The `usecache` flag is now fundamental to all IPNS queries rather than having complex add on code for `FetchProfile` and `FetchImage`. 
All main API calls now have a `usecache` flag. 
Resolve flow works like this:
- On startup nodes are not subscribed to any names. 
- Any Resolve queries first get passed into the pubsub resolver which determines it's not subscribed, subscribes to the name, then returns an error.
- Upon an error from the pubsub resolver the routing resolver tries to fetch the record from the DHT. If the record is found, the local db is updated with the current record. 
- If that fails, we query the pubsub resolver again. This time since it's subscribed, it will return its cache from the database if it has any. 
All subsequent resolves will go …
> IPNS pubsub refactor

- mobile/config.go
- mobile/node.go
The `Node` object in the mobile package provides an easy way to import openbazaar-go as a library and spin up a node inside of another project. 
For use this could be useful for the datanodes and our new relay node as it avoids writing a lot of boiler plate code. 
However, those projects don't need the wallet grinding away in the background so this provides ability to disable it.
> Add disable options to mobile node config

- repo/db/chat.go
- repo/db/chat_test.go
max(timestamp) method was generating NULL in the case when SQL
conditions returned no results, as is the case when no chats with a
peerID have yet been created. Since max(timestamp) does not appear to be
used by anything, let's remove it.
> [Fixes #1041] Remove grouping SQL method from GET /ob/markchatasread

- core/record_aging_notifier.go
Update output from RecordAgingNotifier. Turns:
```
10:33:09.491 [DEBUG] [recordAgingNotifier/PerformTask] performTask started (count 1)
10:33:09.494 [DEBUG] [recordAgingNotifier/generateSellerDisputeNotifications] created 0 vendor dispute notifications
10:33:09.495 [DEBUG] [recordAgingNotifier/generateSellerDisputeNotifications] updated lastDisputeTimeoutNotifiedAt on 0 sales
10:33:09.495 [DEBUG] [recordAgingNotifier/generateBuyerDisputeTimeoutNotifications] created 0 purchase dispute notifications
10:33:09.495 [DEBUG] [recordAgingNotifier/generateBuyerDisputeTimeoutNotifications] updated lastDisputeTimeoutNotifiedAt on 0 purchases
10:33:09.496 [DEBUG] [recordAgingNotifier/generateBuyerDisputeExpiryNotifications] created 0 buyer expiration notifications
10:33:09.496 [DEBUG] …
```
> Simplify logging for RecordAgingNotifier

- core/completion.go
- core/posts.go
- core/profile.go
`defer Close()`'s should be called after checking the potential error returned when the `io.Closer` was created.
Travis passed, but coverage fails because this code is uncovered and there's now more of it even though it's more correct.
> BUGFIX: Call deferred Close() after checking error.

- net/service/handlers.go
- repo/db/cases.go
- repo/db/cases_test.go
- repo/db/chat.go
- repo/db/chat_test.go
- repo/db/db.go
- repo/db/followers.go
- repo/db/followers_test.go
- repo/db/following.go
- repo/db/following_test.go
- repo/db/inventory_test.go
- repo/db/moderatedstores_test.go
- repo/db/notifications_test.go
- repo/db/pointers_test.go
- repo/db/purchases.go
- repo/db/sales.go
- repo/db/settings_test.go
- repo/db/txmetadata.go
- repo/db/txmetadata_test.go
- repo/db/txns_test.go
- repo/migrations/Migration012_test.go
We have many places that do not check returned errors. In most cases an error would have occurred after on a later line of code, but not handling or propagating an error is always an error itself. In two cases the error was not visible because the associated returned pointer was allowed to be nil.
This change propagates those unchecked error the same way surrounding errors are populated.
> BUGFIX: Propagate some previously unchecked errors.

- cmd/start.go
This reverts commit f8640a39cc754a21c94b0ea77a406fbd508b2b67.
It was discovered that syscall.Stdin on Windows is not an int
like on other systems, so it must be converted here.
> BUGFIX: Fix build on Windows

- ipfs/pointers.go
- ipfs/pointers_test.go
This PR refactors the function that extracts the prefix bits from peer ID and returns a pointer key based on the prefix. It can be done much cleaner as a simple bit shift rather than the boneheaded way it's currently being done. It will also make it easier to explain to the UI team how to do it in javascript.
> Perform black magic for pointer key creation

- schema/configuration.go
Add a interface member to the CoinConfig struct to accommodate ETH specific constants like registry contract deployment address,
> Add custom config interface for ETH constants

- cmd/start.go
When starting a fresh node without an initialized schema, the user_agent
will not be written to the schema properly.
> [#1160] Reorder write to {data}/root/user_agent

- api/ws.go
Inbound websocket requests which fail authentication create an error like
"http: response.WriteHeader on hijacked connection" which is unclear. This
will allow authentication to be validated before the connection is hijacked.
> [#1159] Upgrade connection for websocket after validating auth

- api/ws.go
Adding logging to WS handler. 
The global `log` was going into a black hole for some reason. A local instance of logger works, however.
> [#1159] Improve logging in http websocket connection upgrade

- .golangci.yml
- api/jsonapi.go
- cmd/restore.go
- ipfs/cat.go
- ipfs/resolve.go
Add govet checks to linter to catch common issues.
Unkeyed composite literal errors are ignored. I prefer not having unkeyed literals but not everybody feels the same and it shouldn't necessarily be considered an error like most other checks. If we decide we want to remove unkeyed literals we can fix all the occurrences of them and remove the exception.
Also fixes uncancelled contexts caught by govet.
> CI: Add govet to linter

- cmd/start.go
- core/core.go
- core/net.go
- mobile/node.go
Made the duration before the node stops waiting for the online peer to respond and resorts to an offline message a configurable option with hardcoded defaults for the desktop and mobile configurations. The configuration is carried by the `core.OpenBazaarNode` struct as a `time.Duration` and passed in the Context used to send online messages only.
Standard build default is 30 seconds.
Mobile build default is 5 seconds.
> 1191 adjustable offline timeout

- LICENSE
The year in license is currently 2016. I've bumped it to 2018 in order to ensure that no copyright issues arise in the future
> update year in license

- net/retriever/retriever_test.go
This PR addresses #1043.
It adds a test that makes use of the pb.Message_MessageType_value map comparing its values against the contents of net/retriever.MessageProcessingOrder, in addition to a BlackList map for deliberate omissions.
When new message types are added and not included in MessageProcessingOrder (or the BlackList), the unit test suite will fail with:
```
--- FAIL: TestEnsureNoOmissionsInMessageProcessingOrder (0.00s)
Found 1 omission(s): map[FOO:123]
```
> Test for MessageProcessingOrder omissions

- api/jsonapi.go
Was receiving this error on the latest update:
```
api/jsonapi.go:30:2: dshelp redeclared as imported package name
previous declaration at api/jsonapi.go:12:2
```
Removed unnecessary import package
> Fixed import error

- qa/chat.py
Hello,
In my opinion, No time, OrderedDict Python module are required.
Because it is not used.
What do you think of it?
Thanks.
> Remove unused Python modules in qa/chat.py

- vendor/github.com/OpenBazaar/wallet-interface/wallet.go
- wallet/listeners/transaction_listener.go
@cpacia - This is a follow-up PR to the wallet interface changes.
In the transaction listener callback, I have made changes to the fetching of the order/contract details.
When orderID is available in the TransactionInput/TransactionOutput, it will be used to fetch the details else the existing logic of using the output.Address/input.LinkedAddress will be used.
> Use orderID in transaction listener

- core/disputes.go
The temporary check for the bitcoin cash address was added in 2.2.2, released 7/26/2018 and slated for removal no sooner than 45 days. It is now ready for removal from the code. Closes #1244.
> Removed temporary check of bitcoin cash address

- core/listings_test.go
- core/profile.go
- test/factory/listing.go
- wallet/builder.go
- wallet/resync/resync_manager.go
`core.UpdateProfile` was causing currency lists in the profile to become duplicated. Manually verified this fix works for the case illustrated in #1220.
> [#1220] Currencies in profile no longer duplicate on update

- qa/requirements.txt
Change to fix `requirements.txt` so that I can run `pip` against it when building a QA environment.
This is what happens when you run `pip` against the file now:
```
Invalid requirement: 'requests=2.18.4'
= is not a valid operator. Did you mean == ?
```
> Fix requirements.txt operators

- core/core.go
- core/net.go
Fixes #1276. Retry storing initial update with push node via exponential backoff and a little bit of logging.
> Retry failed STORE against push nodes

- README.md
Noticed start flags were slightly out of date. Update to latest. Will need to update this again with the 2.3 release.
> Improve documentation of ob-go start flags

- api/jsonapi.go
- core/refunds.go
- vendor/github.com/OpenBazaar/multiwallet/bitcoin/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go
- vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
- vendor/github.com/OpenBazaar/wallet-interface/wallet.go
- vendor/github.com/cpacia/BitcoinCash-Wallet/sortsignsend.go
@cpacia - Changed the Spend calls in the jsonapi and refunds.
In jsonapi, the send struct will require memo to contain the referenceID/orderID to be passed from the invoker.
> Add referenceID to spend

- api/endpoints.go
- api/jsonapi.go
- core/currency.go
- core/errors.go
This change adds a new possible error to `POST /ob/spendorder`. Our error handling is a little all over the place so it simply returns a string "ERROR_ORDER_NOT_FOUND" if the param is empty or if the order cannot be retrieved. Hopefully we can round back on to the error handling at some point.
> [#1319] Separate spend and spendorder behavior

- repo/init.go
- repo/migration.go
- repo/migrations/Migration015.go
- repo/migrations/Migration015_test.go
- schema/configuration.go
- schema/configuration_test.go
- schema/constants.go
- schema/path.go
- wallet/builder.go
- Reconcile schema.DefaultWalletsConfig()
- Migrate legacy "Wallet" config key to "LegacyWallet" which is ignored
by config handling
- Migrate default "Wallets" config key to contain default multiwallet
settings. Ignores prior fee defaults, but legacy config is intact should
the user decide to restore their prior settings.
- A failure to create a single wallet will no longer impact other
wallets
- Removal of the coin key under the "Wallets" key will disable that
wallet. Alternatively, changing the Type to a value other than "API" and
"SPV" will also disable that coin.
> [#1183] Migrate multiwallet config; Refactor multiwallet config handling

- wallet/listeners/transaction_listener.go
closes #1315 
The listener wasn't switched over to make use of the new input.LinkedAddress field.
> Fix bug detecting resolved dispute

- core/net.go
- net/service/messagesender.go
- net/service/service.go
This fixes the message sending so that it respects the timeout provided with the context.
> Update message sender to respect context timeout when sending messages

- cmd/start.go
- repo/migration.go
Migration counting up always started at 0 instead of on the current migration. Also indicate which schema version is being reached at the end of the migration.
Example:
```
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
/   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
\/|__|        \/     \/       \/      \/      \/     \/     \/
OpenBazaar Server v0.13.0
06:23:15.119 [DEBUG] [core/CheckAndSetUlimit] Did not change ulimit
06:23:15.166 [NOTICE] [repo/MigrateUp] running migration 007 changing schema to version 008...
06:23:15.320 [NOTICE] …
```
> Fix migration counting; Add datadir path hint to Migration014

- .travis.yml
Travis changed it's default `install` behavior to automatically attempt restoring the dependencies defined by `Godep.json`. Since we vendor our dependencies to not require this step, we are replacing the default behavior with a no-op.
> Override travis default install

- core/core.go
- core/net.go
> Add withTimeout to Chat and Offline Messages 

- api/endpoints.go
- api/jsonapi.go
- api/jsonapi_data_test.go
- api/jsonapi_test.go
Per @drwasho's request I whipped up a quick PR to kick this request off, but please be aware this needs conversation and I am not positive it even meets the requirements. 
**/ob/signmessage** -
Input: `{ "content": "<string_content>" }`
Output: `{ "signature": "<hex_encoded_sig>, "pubkey": "<hex_encoded_pubkey>", "peerId": "<peer_id>" }`
**/ob/verifymessage** -
Input: `{ "content": "<string_content>", "signature": "<hex_encoded_sig>", "pubkey": "<hex_encoded_pubkey>", "peerId": "<peerId>" }`
Output: `{ "error": "<empty, PEER_ID_PUBKEY_MISMATCH, or VERIFICATION_FAILED>", "peerId": "<submitted_peerId>" }`
> Sign Verify Content with IPFS Key

- core/order.go
- qa/purchase_direct_offline.py
- qa/purchase_moderated_offline.py
Breaking apart the massive functions in order.go for more clarity and separation of duties cleanup.
> Refactor order.go

- cmd/setapicreds.go
Override ipfs error in `setapicreds`. 
The original error message misled me into spending time figuring out how to set up ipfs, until I realized openbazaar has built in its own verison of it.
This changes the error from:
```
$ go run openbazaard.go setapicreds
2019/02/28 14:01:45 no IPFS repo found in /home/dagurval/.openbazaar.
please run: 'ipfs init'
no IPFS repo found in /home/dagurval/.openbazaar.
please run: 'ipfs init'
exit status 1
```
to:
```
$ go run openbazaard.go setapicreds
The data directory '/home/dagurval/.openbazaar' has not been initialized.
Run openbazaar with the 'start' command to initialize.
exit status 1
```
> Improve NoRepoError message in setapicreds

- mobile/node.go
Upgrading the IPFS repo changed how the ipns key is stored in the db. This means on the first startup after migration there is a key not found error. The code was returning the error rather than ignoring/logging it causing it to fail to start.
> Fix bug starting mobile package

- cmd/setapicreds.go
Currently `setapicreds` is broken as it just adds a section `JSON_API` to the configuration file that isn't read by the server. 
The server is supposed to read it back here:
https://github.com/OpenBazaar/openbazaar-go/blob/master/schema/configuration.go#L133
> Fix json api keyname in setapicreds

- api/endpoints.go
- api/jsonapi.go
- api/utils.go
- api/utils_test.go
- cmd/start.go
- core/moderation.go
- mobile/node.go
- net/networkservice.go
- net/service/service.go
Refactors the notify moderators function. It removes a race condition which could result in the wrong modes being sent notifications. Also waits for the service to start before sending to avoid a panic. 
Also adds blockingStartupMiddleware to purchase post which avoids a panic for trigger happy users. 
Fixes #1502 
Fixes #1451
> Fix NotifyModerators panic if node is not yet bootstrapped

- build.sh
Enforce a specific golang environment when building the server binaries as allowing the latest version was causing the build to fail when attempting to set the ulimit values. `error setting ulimit: invalid argument`
> Enforce golang version during build

- cmd/start.go
Before the password was only handling startup but would not work for
migrations. This will include password handling as part of migrations as
well as startup.
Fixes #1505
> Handle encrypted databases during migration

- cmd/start.go
- vendor/gx/ipfs/QmVSfWChGxC5AkUhM6ZyZxbcBmZoPrUmrPuW6BnHU3YDA9/go-onion-transport/onion_transport.go
There was a conflict registering the TCP protocol in both the onion and tcp
transports when using dualstack mode. This fix makes it so when in dual stack
mode the onion transaction does not register that it can route tcp, only onion.
> Update go-onion-transport to fix bug with dualstack mode

- api/jsonapi.go
When making the request curl localhost:4002/ob/blah -I the method being passed was HEAD. Added this to the switch case and passed as a get request.
Fixes #1527
> #1527 Added Method check for HEAD to validat undefined endpoint

- docs/install-linux.md
- docs/install-osx.md
- docs/install-pi3.md
- docs/install-windows.md
- docs/multipleInstances.md
Adds missing documentation from updating to ob-go project to use go v1.11.5.
Closes #1339
> Update docs to complete 1.11 upgrade

- openbazaard.go
Updating subcommand docs and found these were unimplemented. We can add them again later should we decide we need them. Please confirm that we're not expecting these for any special systemd startup type support. /cc @tyler-smith @cpacia @szollo
> Remove stubbed subcommands Stop and Restart

- README.md
The default golang version on AWS images utilizing `yum install go` point to 1.9 which causes errors during runtime. Adding this blurb should help people resolve this issue.
Here is a sample of the errors if running 1.9
```
go run openbazaard.go start
vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:153:28: undefined: math.Round
vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:428:14: undefined: math.Round
vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:464:14: undefined: math.Round
vendor/gx/ipfs/QmT4U94DnD8FRfqr21obWY32HLM5VExccPKMjQHofeYqr9/go-multiaddr/codec.go:141:10: undefined: strings.Builder
vendor/gx/ipfs/QmT4U94DnD8FRfqr21obWY32HLM5VExccPKMjQHofeYqr9/go-multiaddr/component.go:69:8: undefined: strings.Builder …
```
> Add a blurb about min Golang version in README

- cmd/restore.go
- cmd/start.go
- ipfs/config.go
- ipfs/constants.go
- mobile/node.go
- net/service/messagesender.go
- net/service/service.go
- repo/init.go
- schema/constants.go
Update: This PR also manages the other protocol strings the daemon uses (kademlia, dht legacy, app, and bitswap protocols).
Original Motivation:
So currently we are not setting our DHT routing options correctly for testnet nodes (AFAICT). This means that when publishing and resolving, our testnet nodes just use mainnet DHT and mainnet nodes to store data. This code actually changes that and makes it so we only use testnet nodes. The only problem right now is that there are actually not any nodes that speak this protocol at the moment so it seems like all our testnet nodes will need to upgrade to this code before we see it acting properly (including seed nodes). 
**This needs validation though**
> Fix IPFS protocol identifier handling

- repo/db/chat.go
- repo/db/chat_test.go
- repo/init.go
- repo/migration.go
- repo/migrations/Migration015.go
- repo/migrations/Migration017.go
- repo/migrations/Migration018.go
- repo/migrations/Migration019.go
- repo/migrations/Migration021.go
- repo/migrations/Migration023.go
- repo/migrations/Migration023_test.go
> Increase chat timestamp resolution

- Dockerfile
> CLEANUP: Tweak Dockerfile a little and add comments to make it clearer.

- api/jsonapi.go
- net/networkservice.go
- net/service/service.go
The ban manager only checks to see if a peer is banned if that peer tries to
open a new stream. If there is an existing stream to that peer the messages
would otherwise still get through. This commit changes the behavior to close
the streams to any banned peers which should have the effect of preventing
further communication from them.
> Close stream to peer when the peer is banned

- core/core.go
- core/core_test.go
> Use go-emoji to convert to html chars

- api/jsonapi.go
- api/jsonapi_test.go
- net/service/handlers.go
- repo/api_time.go
- repo/api_time_test.go
- repo/chat_message.go
- repo/db/chat.go
- repo/db/chat_test.go
- repo/db/notifications.go
- repo/models.go
- repo/notification.go
- test/factory/api_time.go
In order to guarantee the formatting and marshaling of timestamp formats, I created `repo.APITime` to protect inputs matching `time.RFC3339` and `time.RFC3339Nano` formats while also having a pattern to follow for future flexibility around time presentation in our JSON API.
Closes #1571
> Create and use repo.APITime to guarantee timestamp formatting in API

- mobile/config.go
- mobile/node.go
This is to support PR https://github.com/OB1Company/native-bazaar/pull/830
on the Haven repo.
> Add logging for mobile nodes

- mobile/node.go
> [#1618] Enable temporary IPv6 bootstrap nodes for mobile package

- cmd/start.go
- ipfs/resolve.go
- ipfs/resolve_test.go
Our IPNS package implements a separate persistent cache for IPNS records. The
format of the value stored in the database is different from the format used
by the DHT package. This commit changes the database key used by the persistent
cache to make sure it does not collide with the key used by the DHT package
which might otherwise cause records to be overriden with a different format.
closes #1612
> Use separate namespace for IPNS persistent cache

- cmd/gencerts.go
- cmd/gencerts_test.go
Continuation of  #1241 in an ob-go branch and rebased with master.
> Unit test for gencerts subcommand

- core/listings.go
- core/listings_test.go
The API would fail if the user had a cryptocurrency listing set since we only
allow one accepted currency for cryptolistings.
This commit changes it to not apply the bulk update to cryptolistings and adds a test.
Closes #1632
> Fix bug in POSTBulkUpdateCurrency API

- api/gateway.go
- cmd/start.go
- core/core.go
- mobile/cmd/main.go
- mobile/node.go
- openbazaard.go
- vendor/gx/ipfs/QmSY3nkMNLzh9GdbFKK5tT7YMfLpf52iUZ8ZRkr29MJaa5/go-libp2p-kad-dht/dht.go
- vendor/gx/ipfs/QmSY3nkMNLzh9GdbFKK5tT7YMfLpf52iUZ8ZRkr29MJaa5/go-libp2p-kad-dht/dht_bootstrap.go
This PR adds a restart method to the mobile node.
> Allow mobile node to be restarted

- api/jsonapi.go
- core/order.go
- core/order_test.go
Extracted method core.GetOrder()
Added unit test for it
> Extract GETOrder behavior into unit testable method #1483

- api/endpoints.go
- api/jsonapi.go
- api/jsonapi_data_test.go
- api/jsonapi_test.go
- repo/currency.go
- repo/currency_definition.go
- repo/currency_definition_test.go
- repo/currency_definitions_validity_test.go
- test/factory/currency.go
Work towards completion of #1586.
Some example output:
```
[1586-currency-dictionary][mg@io:~/go/src/github.com/OpenBazaar/openbazaar-go]
[10:04:41] $ curl -I 0.0.0.0:4002/wallet/currencies/BCH
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 27 Aug 2019 14:04:51 GMT
Content-Length: 184
[1586-currency-dictionary][mg@io:~/go/src/github.com/OpenBazaar/openbazaar-go]
[10:04:52] $ curl -I 0.0.0.0:4002/wallet/currencies/INVALID
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Tue, 27 Aug 2019 14:04:58 GMT
Content-Length: 72
[1586-currency-dictionary][mg@io:~/go/src/github.com/OpenBazaar/openbazaar-go]
[10:06:07] $ curl 0.0.0.0:4002/wallet/currencies/INVALID
{
"success": false,
"reason": "unknown definition for INVALID"
}
```
Full dictionary response: …
> Add GET /wallet/currencies

- .gitignore
- api/jsonapi.go
- core/confirmation.go
- net/service/handlers.go
- wallet/listeners/transaction_listener.go
OrderConfirmation has lots of opportunities to be left in a bad state. This makes some changes which help recover some unexpected side-effect when failing mid-way through transition with a TODO to follow up on later.
Fixes #1668 and then some.
Note: This is built off the `numprec` branch and will merge onto the precision work to avoid annoying reconciliation later.
> Improve OrderConfirmation failure recovery

- vendor/github.com/OpenBazaar/go-ethwallet/wallet/client.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
This PR addresses the issues #1418 and #1431.
There is a balance check in place before a call to multisign is made.
Also, the spendAll flag is now checked before transfer.
> Fix 1418 and 1431

- core/order.go
- repo/currency.go
- repo/currency_test.go
Fixes #1747 
Some places we might be okay with dropping significant figures (such as when converting a higher divisibility currency into a lower divisibility currency, some significant figures will be lost). Instead of erroring, we will expose the big.Accuracy result out of `CurrencyValue.ConvertTo` so the caller can make the decision for themselves.
Accuracy(1) means the result is `Above` the actual converted value and Accuracy(-1) means the results is `Below`.
> Express accuracy outside of Currency conversion

- repo/listing.go
- repo/listing_test.go
Fixes #1736 
Ensures all versions of schema values are properly represented out of `repo.Listing.GetCryptoDivisibility()`
> Express repo.Listing.CryptoDivisibility as exponential value

- net/retriever/retriever.go
This fixes the issue that if messages came from an offline relay out-of-order they would never end up getting processed.
> Added relay messages to MessageProcessingOrder

- api/jsonapi.go
- cmd/start.go
- core/core.go
- core/net.go
- core/profile.go
- ipfs/config.go
- ipfs/pubsub.go
- ipfs/resolve.go
- mobile/node.go
- net/retriever/retriever.go
- net/service/handlers.go
- repo/migration.go
- repo/migrations/Migration026.go
- repo/migrations/Migration026_test.go
- repo/migrations/log.go
Fixes #1800 
Some observations from this work:
- ob-go does not put full IpnsEntry records into the IPFS Repo Datastore. If there invalid data being injected, it's by another system.
- Migration020 migrates IPNS records to key other than what we use for lookups in ipfs.Resolve (bug?) (see the difference in the keys used in Migration020 and the ones defined in `nativeIPNSRecordCacheKey` vs `obIPNSCacheKey`)
> IPNS improvements to prevent panic

- core/utils.go
This code was trying to avoid an edge case where multiple outputs in the
same transaction paid the payment address but this should already have
been accounted for when the record was saved in the db and the values
already aggregated. Thus this was causing incorrect amounts to be saved.
closes #1499
> (#1499) Fix double amount in payment record

- core/record_aging_notifier.go
- core/utils.go
- repo/db/cases.go
- repo/db/chat.go
- repo/db/coupons.go
- repo/db/db.go
- repo/db/followers.go
- repo/db/following.go
- repo/db/inventory.go
- repo/db/keys.go
- repo/db/messages.go
- repo/db/moderatedstores.go
- repo/db/notifications.go
- repo/db/offinemessages.go
- repo/db/pointers.go
- repo/db/purchases.go
- repo/db/sales.go
- repo/db/settings.go
- repo/db/stxo.go
- repo/db/txmetadata.go
- repo/db/txns.go
- repo/db/utxos.go
- repo/db/watched_scripts.go
Help improve #1572 but was not able to find the root cause for the unmarshal error. @amangale if you can provide more insight, I might be able to reproduce it but I was not able to.
This PR mainly removes unused transactions on the database and uses the `modelStore` interface methods instead of reaching into each datastore's private variable. It also does not use the node state to deteremine which currencies are accessible via the `OpenBazaarNode.CurrencyLookup()` method.
Closes #1572
> (#1572) Record aging improvements

- wallet/listeners/transaction_listener.go
Fixed #1836 
The problem in this issue is that we're trying to validate the buyer's provided divisibility against the listing's divisibility but that field is not used in the listing for crypto listings causing a panic. 
Question for @placer14: 
This comment
> // TODO: this comparison needs to consider the possibility of different divisibilities
Doesn't seem to apply here right as if we skip the code block which assigns a custom divisibility in the crypto listing case then we're never using a custom divisibility. It's always using the divisibility from the lookup() right?
> (#1836) Only validate divisibility in sales listener if not crypto listing

- core/spend.go
- net/service/handlers.go
- vendor/github.com/OpenBazaar/go-ethwallet/util/util.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/account.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/erc20_wallet.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/service.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Earlier, there were places where the `0x` prefix was being trimmed before being sent to ob-go. This is not removed. All the txn ids/hashes/addresses will not be trimmed of their `0x` prefix.
> (ob-desktop #1825) Use ethereum transaction hash as is

- core/order.go
The crypto listing total calculation code was not adjusting for the payment
coin's level of precision and thus was returning only a few digits when
paying with eth instead of the full precision.
closes #1835
Sadly our code does not allow any easy way to test this without hitting the exchange rate API. We need much more refactoring, if not a whole sale change to the wallet interface and exchange rate design to improve. 
But for the sake of manual testing you can use this function:
```go
func TestCryptoListingTotal(t *testing.T) {
node, err := test.NewNode()
if err != nil {
t.Fatal(err)
}
contract := &pb.RicardianContract{
VendorListings:          []*pb.Listing{
{
Slug:                 "test",
Metadata:             &pb.Listing_Metadata{
Version:              5,
ContractType: …
```
> (#1835) Fix cryptolisting price calculation for ETH payments

- cmd/start.go
This adds date to timestamps in the logs for the desktop server.
> Add dates to timestamps for desktop server

- core/order.go
> (#1834) Do not allow purchases if amount is lower than the wallet's dust amount

- mobile/node.go
Currently we just output the time and this makes it hard to find certain days in the log files.
> Add date to the timestamps in Haven logging

- core/profile.go
- repo/profile.go
- repo/profile_test.go
- test/factory/profile.go
Fixes #1881 
Also attempts to read/write from the old profile schema in case the node is reading a v4 schema node's profile. The v4 schema data will not be available if the FixedFee amounts exceed the available precision. (This behavior contributes to #1904 but may not complete it.)
> (#1881) Check for non nil moderator fixed fee amount

- core/images.go
- net/retriever/retriever.go
Revert back to original transports for the message retriever and image retrieval.
> Fix transports for message retriever and images

- core/images.go
- core/spend.go
- net/retriever/retriever.go
- net/service/handlers.go
This is fixed in ethereum-master btw.
Fixes #1907
> (#1907) Check for empty peer ID before adding to spendResponse

- core/refunds.go
This should close #1815.
I was unable to reproduce the missing data part of the issue though Rob did say the data eventually came in. Afaict this is the only place where the CurrencyValue is set (and it was missing) so I'm not sure how Rob was able to see it set in another context.
> (#1815) Add currency value to refundAddressTransaction

- api/jsonapi_test.go
- core/profile.go
- repo/listing.go
- repo/profile.go
This PR adds some tests which protect the `PATCH /ob/profile` response and ensures a few of the moderator fee scenarios work as expected.
Fixes #1879
> [#1879] Ensure PATCH /ob/profile returns appropriate response

- core/order.go
- repo/db/purchases.go
I'm sure this is not a long term fix considering there should be a migration of pre-ETH contracts to the new payment refactor, but it does alleviate the panic when loading orders into the UI.
Fixes #1846
> (#1846) Unable to load legacy orders due to payment coin refactor

- Dockerfile.dev
- Dockerfile.qa
- Makefile
- build_qa.sh
- qa/runtests.sh
Fixes #1892 
Now pulls in code that is triggering the QA test suite and also now exits out of the sub-scripts if there is a unit test failure.
> (#1892) QA Runner

- vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go
These changes satisfy concerns in #1918 and rescues/corrects old order transactions
> Do not mark wallet address as watched + fix earlier txn errors

- core/images.go
- core/order.go
- net/retriever/retriever.go
- net/service/handlers.go
- repo/db/watched_scripts.go
- vendor/github.com/OpenBazaar/bitcoind-wallet/wallet.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/erc20_wallet.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/bitcoin/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
- vendor/github.com/OpenBazaar/multiwallet/client/pool.go
- vendor/github.com/OpenBazaar/multiwallet/datastore/mock.go
- vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/model/interfaces.go
- vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go
- vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go
- vendor/github.com/OpenBazaar/spvwallet/wallet.go
- vendor/github.com/OpenBazaar/wallet-interface/datastore.go
- vendor/github.com/OpenBazaar/wallet-interface/wallet.go
- vendor/github.com/OpenBazaar/zcashd-wallet/wallet.go
- wallet/resync/resync_manager.go
Helps fix #1919 
This will hopefully fix:
- https://github.com/OpenBazaar/openbazaar-go/issues/1659
- https://github.com/OpenBazaar/openbazaar-go/issues/1363
> (#1919) Migrate to AddWatchedAddresses

- core/completion.go
This issue fixes the scenario where the BUYER released the funds but the SELLER did not receive the completion message (but likely did receive the coins).
> [#1681] Protect POSTReleaseEscrow sweep when there are no inputs

- net/retriever/retriever.go
> (#1938) Improve Offline Message Debugging Log

- Godeps/Godeps.json
- vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
We currently send [ "command", "addr1", "addr2" ... ] to BlockBook when it should be [ "command", [ "addr1", "addr2" ] ].
Fixes #1963
> Send addresses as slice to BlockBook

- Godeps/Godeps.json
- qa/eth_purchase_crypto_listing.py
- qa/purchase_crypto_listing.py
- qa/runtests.sh
- qa/runtests_eth.sh
- qa/testdata/eth_listing_crypto.json
- qa/testdata/listing_crypto.json
- qa/testdata/order_crypto.json
- qa/testdata/order_direct_too_much_quantity.json
- vendor/github.com/OpenBazaar/multiwallet/bitcoin/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go
- vendor/github.com/OpenBazaar/spvwallet/.travis.yml
- vendor/github.com/OpenBazaar/spvwallet/Dockerfile.dev
- vendor/github.com/OpenBazaar/spvwallet/Gopkg.lock
- vendor/github.com/OpenBazaar/spvwallet/docker-compose.yml
- vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
- vendor/github.com/OpenBazaar/spvwallet/wallet.go
What is happening is the QA test is testing the "not enough inventory" case but in doing so it's setting the purchase quantity to 999999999999. This is resulting in an order total that, while it fits in a big int, does not fit in a the int64 used by the wallet's `IsDust` method and thus is wrapping around zero and causing the `IsDust` check to return True. By setting the purchase quantity to a lower but still too high amount we get around the problem and can test the not enough inventory case. 
Fixes #1981
> Fix failing QA test due to dust amount

- Godeps/Godeps.json
- qa/eth_escrow_release_after_timeout.py
- qa/test_framework/test_framework.py
- qa/testdata/eth_listing.json
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
This PR fixes the reverse chronological ordering of eth txns. It also adds a tor flag to the qa script.
> Fix transaction ordering and enable Tor flag for the qa script

- cmd/start.go
- core/moderation.go
- core/order.go
- core/order_test.go
- core/utils.go
- mobile/node.go
- repo/currency.go
- repo/currency_converter.go
- repo/currency_test.go
- test/factory/currency_converter.go
Isolated the conversion behavior within ConvertTo to live within
repo.CurrencyConverter. It will be provided with a rater interface with
a single method requirement that is satisfied by a subset of today's
wallet-interface.ExchangeRates interface. This change eventually leads
to a wallet-independent exchange rate service which can be separated
later.
Supercedes https://github.com/OpenBazaar/openbazaar-go/pull/1949
Fixes https://github.com/OpenBazaar/openbazaar-go/issues/1983
> (*repo.CurrencyValue).ConvertTo accepts a *repo.CurrencyConverter

- core/order.go
- core/order_test.go
- repo/currency.go
- repo/currency_test.go
When processing the order total for contracts with legacy listings, they did not access the data properly in all cases. These changes ensure all access is done through a normalized `repo.Listing`.
Fixes #1983
> (#1983) Calculate order total w normalized listings

- core/order.go
- qa/test_framework/test_framework.py
- repo/currency_converter.go
Forgot to support testnet when creating reserve currency converter. This will enable testnet/regtest to work normally.
> [#1983] Support testnet reserve currency converter usage

- vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
- vendor/github.com/cenkalti/backoff/LICENSE
- vendor/github.com/cenkalti/backoff/README.md
- vendor/github.com/cenkalti/backoff/backoff.go
- vendor/github.com/cenkalti/backoff/backoff_test.go
- vendor/github.com/cenkalti/backoff/context.go
- vendor/github.com/cenkalti/backoff/context_test.go
- vendor/github.com/cenkalti/backoff/example_test.go
- vendor/github.com/cenkalti/backoff/exponential.go
- vendor/github.com/cenkalti/backoff/exponential_test.go
- vendor/github.com/cenkalti/backoff/go.mod
- vendor/github.com/cenkalti/backoff/retry.go
- vendor/github.com/cenkalti/backoff/retry_test.go
- vendor/github.com/cenkalti/backoff/ticker.go
- vendor/github.com/cenkalti/backoff/ticker_test.go
- vendor/github.com/cenkalti/backoff/timer.go
- vendor/github.com/cenkalti/backoff/tries.go
- vendor/github.com/cenkalti/backoff/tries_test.go
Here is some code that uses the backoff library to exponentially back off when retrying websocket connections to the Blockbook servers. Currently we just infinitely try every 2 seconds and this spikes the CPU dramatically.
> Exponential Backoffs for Socket Connection to Blockbook

- repo/db/sales.go
Problem: When pulling extremely large numbers out of SQLite as a string type but the Go scanner will convert the string using reflection into a scientific notation string. 
Proposed Solution: Check if reflected string has an 'e' in it then we identify it as a scientific notation and convert it back to a large number in a string.
> Values from DB that get reflected into scientific notation are kept as strings

- core/disputes.go
- core/net.go
This PR is designed to save more outgoing messages so they can be replayed if there is some message handling error by the recipient. This is useful especially in Haven where we've baked into the app logic to resend old order messages to give the best chance at preventing orders from being stuck.
The following order messages are saved into the database:
| Order message | [Message #](https://github.com/OpenBazaar/openbazaar-go/blob/ethereum-master/pb/protos/message.proto#L14) | Sent by | Tested |
| --- | :---: | :---: | :---: |
| ORDER_PAYMENT | 21 | Buyer | ✅ 
| DISPUTE_OPEN | 10 | Buyer/Seller | ✅ |
| DISPUTE_UPDATE | 11 | Buyer/Seller | ✅ |
| DISPUTE_CLOSE | 12 | Buyer/Seller | ✅ |
| REFUND | 13 | Seller | ✅ |
The checked-off items are the ones I've tested to for their presence in the …
> feat: Save outbound order payment, refund, and dispute messages

- vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
If Etherscan API does not know about the tx yet, just return no confirmations.
> Return no confirmations if endpoint is not aware of the tx

- core/disputes.go
- net/service/handlers.go
- qa/testdata/eth_listing.json
- repo/db/sales.go
- vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
- vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
This PR fixes issue #2002 #2005 #2006 #2012
> (#2002, 2005, 2006, 2012) Handle zero mod fee

- repo/listing.go
- wallet/listeners/transaction_listener.go
closes #1943
The bug here was try to set the divisibility in the notification to a custom divisibility found in the listing but the would result in overriding a crypto divisibility such as 8 or 18 with a fiat divisibility of 2. 
Since we aren't going to be doing custom divisibilities anytime soon I just removed this code block.
> (#1943) Fix currency value in order notification

- net/service/handlers.go
These changes + Haven app frontend changes to check for vendor-accepted payment dispute terms should fix issue #1651
> Added orderConfirmation state check

- repo/db/purchases.go
This shouldn't be an issue since the notation fix was in, but just in case data comes out of the db in this form we protect against it.
See bug from @drwasho
> Fix scientific notation coming out of database for purchases

- core/disputes.go
> Changed ReleaseFunds func to check if transaction goes through before saving 

- api/endpoints.go
- api/jsonapi.go
This will take a string and encode it as a multihash + convert it to a Base 58 string in the same way we do to our coupons. This makes it easy for clients to determine if a given coupon matches a listing's coupon secret.
> feat: Endpoint to hash a message

- net/service/handlers.go
- wallet/listeners/transaction_listener.go
Save DisputeAcceptance data to the contract.
Also automatically progress an order contract's state to RESOLVED when a DISPUTE_CLOSE message is found and DisputeAcceptance data is already present on the contract.  This is another fix aimed at fully resolving #1651
>  Fix: Save DisputeAcceptance to the contract no matter what

- vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
> Save and load unconfirmed txs from db

- wallet/listeners/transaction_listener.go
When we see txs for orders then we should scan them to ensure their db state matches where the contract is.
> Cleanup Order State

- core/order.go
- qa/testdata/v5/order_crypto.json
We were assuming all listings were for cryptos with base unit of 8 digits. This uses the actual precision from the listing itself.
> Fix purchase crypto test

- repo/db/purchases.go
Some orders in the database table have no total specified and will show no value in the Purchases table.
> Fix purchases tab for broken orders

- api/jsonapi.go
By modifying the contract we generated a new order ID and were updating that in the database. We're only trying to get the correct amount from a legacy contract, not to change the contract itself.
> Do not use updated contract as update into db

- core/moderation.go
- core/profile.go
Any disputes from v4 carried over to v5 who have a moderator with FIXED FEE or FIXED FEE PLUS will have issues closing disputes or viewing. This should address that.
> Fix fixedfee disputes from v4

- api/endpoints.go
- api/jsonapi.go
- core/order.go
- repo/checkout.go
This enables checkout breakdown call to get an itemized breakdown of an order.
The format to make the call is as follows:
```json
{
"shipTo": "Elwood Blues",
"address": "1060 W Addison",
"city": "Chicago",
"state": "Illinois",
"countryCode": "UNITED_STATES",
"postalCode": "60613",
"addressNotes": "",
"items": [
{
"listingHash": "QmTjLBaqrunGmvCD9A3joXLXGudAwxnQvMtvcggQ5rahxN",
"bigQuantity": "1",
"options": [
{
"name": "Sizes",
"value": "Small"
},
{
"name": "Color",
"value": "Red"
}
],
"shipping": {
"name": "Worldwide",
"service": "Standard"
},
"memo": "thanks!",
"coupons": []
}
],
"moderator": "QmcdkKM2fWCKzTZdpjEY6abzRbDhRRJvNmqwNKVyiDtGky",
"paymentCoin": "LTC"
}
```
This call returns:
```json
{
"basePrice": "45433155",
"coupon": "4543316",
"optionSurcharge": "9086631", …
```
> Add /ob/checkoutbreakdown Endpoint

- util/utils.go
This is causing checksum validation issues for addresses where 0x appears in the middle of the address not just at the beginning.
> Do not strip 0x in the middle of the string

- vendor/github.com/OpenBazaar/multiwallet/zcash/sign.go
In order to fix for latest ZCash hard fork. Tested successfully.
> Update ZCash consensus branchID to Canopy
